### ISSUE TITLE
transcoded songs are played next in the queue even if you are listening to a different album

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#106]
yeah another bug report from me, sorry xD

well yesterday i was listening to an album while transcoding another one. Just after the album finished transcoding it was played by tauon superseding the other album, is this a bug or it's intentional?because it's a weird thing and definitely not expected...

**Comment by Taiko2k** [comment]
We're sorry, we have received too many issue submissions from your account. Your IP address has now been banned.

That was a joke, its fine! Certainly, the transcoder should have no effect on what order things are played.

Could you give exact steps to replicate? I'm guessing it may be an issue with having `Playback follows cursor` enabled. Because when you right click something, that track becomes selected. So that would therefore be expected behavior if the queue had reached its end, but not if there were still more items in the queue.

**Comment by legacychimera247** [comment]
1 play an album (eg album 1)
2 transcode album 2
3 when the transcode it's finished album 1 automatically stops and album 2 starts playing

don't know if it's intentional but seems even that if i am listen to a song and i click (single click) on another one, this song gets played after the currently playing one...

**Comment by Taiko2k** [comment]
Yes, I assume you have `Playback follows cursor` enabled. So that is intentional with that setting enabled. :smiling_imp:

**Comment by legacychimera247** [comment]
ok so i just need to disable this one, fair enough...

**Comment by Taiko2k** [comment]
Ill rename this to "Playback follows selected" to make it more clear. I only used the word "cursor" because its what other players use, but it doesn't really make sense in this context I don't think, or at least, it doesn't fit in the existing terminology.
