### ISSUE TITLE
open only the current artist if selected on artist view

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#109]
the artist list is very good, exactly what i was looking for, it would be nice anyway if clicking on an artist could bring up only the selected artist instead of the whole list, like the sort "Artist: Madonna" is already doing, so we can have only records for that artist, maybe (if it's doable) with a switch somewhere to deselect that because not everyone may agree...

**Comment by Taiko2k** [comment]
You can filter to a new playlist using a right click then left click, I wonder if that is satisfactory?

**Comment by legacychimera247** [comment]
what about making the right click already doing the action?

**Comment by Taiko2k** [comment]
Might want to keep the right-click context menu since it might be useful to add other things to it in the future.

My new solution I have is to keep the current behavior, but if you use `Filter artist to new playlist`; in that new playlist (that is titled like "Artist: Madonna") the artist list will now stay linked to the originating playlist, and clicking (left click) will then behave as you describe; acting like a filter where it replaces the tracks to just show the clicked artist.

**Comment by Taiko2k** [comment]
To summarize, this now works if you create a "special" playlist using that right-click option. Hopefully this is a good compromise. I want to avoid adding *temporary filters* or cluttering the settings panel too much.
