### ISSUE TITLE
[Feature request] When metadata of a track is changed, automatically re-fetch scrobble count for it

### ISSUE THREAD

**Issue by rexendevar** [Taiko2k/TauonMusicBox#1121]
Some songs in my library are not titled the same way they are on Spotify, which means they are not marked as the same song on Last.fm. This especially happens when titles contain diacritics or ellipses, as Musicbrainz (the service I use for fetching metadata) stores those as different characters. Thus, when I realized that the song "Searching..." by King Gizz was listed as having no scrobbles, I retitled it with the correct characters. At this point I would expect Tauon to re-fetch the scrobble count automatically as the scrobble data is very likely to be different. Instead it still shows zero scrobbles and I don't much want to restart the program while I'm still listening to see if it updates.

**Comment by Taiko2k** [comment]
The issue is the concept of a scrobble count doesn't exist in the last.fm api. The way Tauon gets this information is to page over the users entire listening history then summing that which can take on the scale of hours to complete if rate limits are respected, it's not feasible to do this on a per track basis. Perhaps a form of data caching could help elevate this but it's more complexity than im enthusiastic to get into.

**Comment by rexendevar** [comment]
Damn, that's a pain. Thank you for your response
