### ISSUE TITLE
Is there a way to lower (and possibley elimintate) the background transparency?

### ISSUE THREAD

**Issue by keystroke3** [Taiko2k/TauonMusicBox#113]
The album cover art thing works. Thanks for including that. Is there a way to turn down the transparency. I can hardly see the the difference that the new feature makes. It is there, but easy to miss. I believe it is the transparency that hurts the background cover visibility.

**Comment by Taiko2k** [comment]
You can select "stronger" to reduce the background opacity a bit more, but due to a technical limitation I can't reduce it much more than that (its complicated). Either way, I don't think it looks good having the image more or very opaque. (Drawing text etc directly onto an album image looks horrible.)
