### ISSUE TITLE
Double albums

### ISSUE THREAD

**Issue by StrangeSeasOfThought** [Taiko2k/TauonMusicBox#139]
How does the app handle double albums? It's not making use of the disc tag, right?

My folder structure:

NELL/Healing Process/CD 1/Tracks
NELL/Healing Process/CD 2/Tracks

Tracks are tagged with disc: 1 / disc: 2.

CD 1 and CD 2 are counted as seperate albums in settings -> stats; and are listed as such in playlist and gallery.

**Comment by Taiko2k** [comment]
In almost all places, one folder = one album. The tags are mostly ignored for the purposes of grouping albums.

If you have a 2+ CD album with all tracks in a single folder, it will attempt display those in the correct order by reading the disc numbers. The folder will still only count as one album.

**Comment by StrangeSeasOfThought** [comment]
Ok, thanks.

**Comment by Taiko2k** [comment]
I have revised the album count algorithm on the stats page now. It now counts unique album tags with a limit of one per folder. Heres how it affects the stats for me:

- 2630 : Unique album fields
- 2614 : Unique folders (previous algorithm)
- 2510 : Combined unique

But, I think thats too low now because albums without an album tag will not be counted again

- 2566 : Combined unique + allow empty album field

Soo, I assume thats more accurate now.

**Comment by legion1978** [comment]
i was wondering how to make 2cd albums in separate folders show up as one album in the playlist. will this accomplish that? or is it just for stats? thnx

**Comment by Taiko2k** [comment]
@legion1978 That was just for the stats. Although, I was thinking of combining multi-cd albums in the gallery... though doing this for the playlist may be an issue because functions like modify folder, rename tracks etc all only operate on single folders.
