### ISSUE TITLE
Enhancement: Ratings

### ISSUE THREAD

**Issue by StrangeSeasOfThought** [Taiko2k/TauonMusicBox#150]
Read and display ratings from file:

FMPS_Rating

0.10 = 0.5 Star
0.20 = 1 Star
0.30 = 1.5 Stars
0.40 = 2 Stars
0.50 = 2.5 Stars
0.60 = 3 Stars
0.70 = 3.5 Stars
0.80 = 4 Stars
0.90 = 4.5 Stars
1.00 = 5 Stars

**Comment by Taiko2k** [comment]
Since early on in the design of Tauon Music Box, I avoided including set-able ratings as a feature, mainly because I felt that the writing of user ratings to tags is a bad concept. So I don't have intention of implementing that. 

Therefore in turn, with not being able to write them, I don't see it would make sense for Tauon to be able to read or show these either.

**Comment by StrangeSeasOfThought** [comment]
Well, one can easily set ratings via a tag editor, so that's not something I care about. But being able to  display them would be great, especially for creating playlists based on ratings.

**Comment by necrophcodr** [comment]
> Well, one can easily set ratings via a tag editor, so that's not something I care about. But being able to display them would be great, especially for creating playlists based on ratings.
> 
> I mostly listen with shuffle enabled, but shuffle also picks up intros, interludes, outros, skits, and other tracks I don't really want to listen to.

Surely for that you can avoid adding those tracks to your playlist?

**Comment by StrangeSeasOfThought** [comment]
> Surely for that you can avoid adding those tracks to your playlist?

The whole point is not having to do this manually. I use another music player that can create smart playlists based on e.g. ratings and then import the playlists into Tauon Music Box. That's somewhat annoying but still 100x better than having to do this manually.

**Comment by DesertStars** [comment]
> Since early on in the design of Tauon Music Box, I avoided including set-able ratings as a feature, mainly because I felt that the writing of user ratings to tags is a bad concept. So I don't have intention of implementing that.
> 
> Therefore in turn, with not being able to write them, I don't see it would make sense for Tauon to be able to read or show these either.

What about making ratings independent of tags, for example in a way that you can set a rating for an album in TauonMusicBox but it only stays within TauonMusicBox, attaching rating metadata to TauonMusicBox instead of the files themselves, so if you opened the files with a tag editor there wouldn't be any tags related to ratings. I'm not sure if that's feasible though or even a good approach.

**Comment by Taiko2k** [comment]
> What about making ratings independent of tags

I had thought of this, buy I worried it may be confusing to users if it doesn't write to tags. Like a user might be frustrated if they expected tags to be written, but then later found out they were not.

What I think would be cool is if a site like Rate Your Music had an API that could be used to store and retrieve ratings, in a similar way last.fm allows loving and un-loving tracks. Unfortunately RYM doesn't have an API. Their work in progress site Sonemic makes mention of an API so maybe they will have such functionality in the future (Though at this rate we will be waiting 'till 2030).

___

Aside from that, the other issue I have is where in the UI to put them. The obvious place would be to the left of the duration in the tracklist, but the playtime indicator and love indicators to there, it would be very cluttered to allow the user to enable all 3 at the same time?

Possible solutions:
 - Just allow the user to enable them anyway
 - Only have album ratings (since it would be less cluttered)
 - Only show ratings in columns view
 - Hide ratings behind a keyboard button hold

I personally don't use ratings and see having the feature as cluttering. I also wonder if having ratings is a good feature to encourage... I realise that may seem unfair to people who manage their library differently, but I wonder if there is a better solution for how people use ratings, or what they are trying to achieve with ratings, like, would a "ban"/"disable" feature (like, an opposite to "love") make more sense?

**Comment by StrangeSeasOfThought** [comment]
> Aside from that, the other issue I have is where in the UI to put them. The obvious place would be to the left of the duration in the tracklist, but the playtime indicator and love indicators are also there. It would be very cluttered to allow the user to enable all 3 at the same time?

I always thought of them as a third display option instead of playtime lines and playtime stars. The same for column view (Starline column), or perhaps their own column.

**Comment by Taiko2k** [comment]
> I always thought of them as a third display option instead of playtime lines and playtime stars.

Yeah, something like this (wip)

![Screenshot from 2020-02-24 01-12-05](https://user-images.githubusercontent.com/17271572/75111812-c8191880-56a2-11ea-9414-c514d4b051e2.png)

**Comment by StrangeSeasOfThought** [comment]
Any chance for half stars, though?

**Comment by DesertStars** [comment]
> > I always thought of them as a third display option instead of playtime lines and playtime stars.
> 
> Yeah, something like this (wip)
> 
> ![Screenshot from 2020-02-24 01-12-05](https://user-images.githubusercontent.com/17271572/75111812-c8191880-56a2-11ea-9414-c514d4b051e2.png)
> 
> Do we need 1/2 stars (0-10)? or is full stars acceptable (0-5)?

This looks super good, I also think half stars would be better. Is there any way that this could be applied to albums as well?

**Comment by Taiko2k** [comment]
OK I've pushed what I have here so far. (There's some slight visual changes)

Note that it might be unstable, i havent tested it much, also, downgrading is not supported once you update to this version.

@StrangeSeasOfThought Btw, this update changes how the `rat` sorter works. It now take the local rating, which is now a value from 0 to 10. If you want FMPS_Ratings, you can import them by, MENU > Database > Import ratings from FMPS tag (hidden unless shift is held)

> Is there any way that this could be applied to albums as well?

Yes, Ill look into this later.

**Comment by StrangeSeasOfThought** [comment]
Okay. I guess, I can update the local file the same way? Just import ratings again?

**Comment by Taiko2k** [comment]
@StrangeSeasOfThought Pressing `Import ratings from FMPS tag` will, as a one off, overwrite local tracks ratings with the FMPS tag value if present. (the tag value is still only read when you do a tag scan)

**Comment by StrangeSeasOfThought** [comment]
Importing ratings via FMPS worked flawlessly. Right now only loved tracks or ratings can be displayed. The heart should be displayed left of the stars, imo.

Because I only use columns view, please implent user ratings there, too. I'd be fine with showing user ratings in the starline column.

**Comment by StrangeSeasOfThought** [comment]
> > Is there any way that this could be applied to albums as well?
> 
> Yes, Ill look into this later.

An album should just display the average rating of rated tracks within the album, instead of users being able to rate an album, imo.

**Comment by StrangeSeasOfThought** [comment]
> Btw, this update changes how the `rat` sorter works. It now take the local rating, which is now a value from 0 to 10. If you want FMPS_Ratings, you can import them by, MENU > Database > Import ratings from FMPS tag (hidden unless shift is held)

After importing FMPS_Ratings, the rat sorter doesn't work at all. I tried both old and new (e.g. 0.8 and 8).

**Comment by Taiko2k** [comment]
Ive pushed another update. This should fix the rating sorter, hearts can now be enabled alongside ratings, and theres now a "Ratings" column.

There's some important fixes to some bugs that cause corruption, so I recommend **upgrading asap** if you're using that version for your main.

___

> III) Studio album track automatically received the rating.

Yes, that's more or less intentional. (If you really want to avoid it, you can do so by making the tracks have different filenames.)

> IV) Single album track lost the rating.

This *shouldn't* happen just by importing I don't think, can you confirm this behavior?

**Comment by StrangeSeasOfThought** [comment]
![library](https://user-images.githubusercontent.com/43582772/75131537-d2073f80-56d3-11ea-9e23-8b21078310bc.gif)

<3

**Comment by StrangeSeasOfThought** [comment]
> This _shouldn't_ happen just by importing I don't think, can you confirm this behavior?

It didn't work for a single album with two different versions of the same track either despite different filename:

... (Original Sound Track Ver.)
... (Radio Edit Ver.)

Only first one showed the rating.

**Comment by Taiko2k** [comment]
@StrangeSeasOfThought That's a lot'a ratings... :open_mouth:  
___

> It didn't work for a single album with two different versions of the same track either despite different filename:

To clarify, for the purposes of rating, playtimes and loves, a track is uniquely identified by a matching **title**, **artist** and **filename**.

There are some functions that move these around such as "Rename tracks", and "Vacuum tracks", but importing tracks should have no effect.

**Comment by StrangeSeasOfThought** [comment]
Yeah, well, just reporting.

![ratings](https://user-images.githubusercontent.com/43582772/75132581-c289f580-56d7-11ea-82df-c727a118e45e.png)

**Comment by StrangeSeasOfThought** [comment]
Re-importing from FMPS_Rating didn't work for these tracks.

**Comment by StrangeSeasOfThought** [comment]
I re-imported from FMPS and a previously unrated track received 4 stars. So far so good. But the previous track in the playlist went from 4 stars to 3.5 despite a correct FMPS rating of 0.80.

**Comment by StrangeSeasOfThought** [comment]
Columns view: Auto resize doesn't work for ratings column.

**Comment by Taiko2k** [comment]
> Columns view: Auto resize doesn't work for ratings column.

Fixed.

___

I've now added a config file option `write-ratings-to-tag` which when enabled will update the FMPS_Rating on the file when setting a tracks rating. It only works for MP3 and FLAC though (for flac, you will need the package `flac` installed`)

You might wanna double check that its working as expected before using it on your main music collection though.

And keep on the lookout for other odd behavior. I think I might have noticed some strange things as you mentioned.

**Comment by StrangeSeasOfThought** [comment]
> I've now added a config file option `write-ratings-to-tag` which when enabled will update the FMPS_Rating on the file when setting a tracks rating.

That's awesome! I didn't dare to ask for it because you were against it previously. ^^
I think I'd prefer this to be a menu option, though: 'Write ratings to tags'. Instead of immediately updating the file...

**Comment by Taiko2k** [comment]
> Rather than immediately updating the file...

You might lose track of which ones you have changed though wouldn't you?

**Comment by StrangeSeasOfThought** [comment]
> You might lose track of which ones you have changed though wouldn't you?

I'd just update the files soon after rating them, all my tracks are already rated anyway, so it'd only be in case of a new album release. Having a menu option is like asking 'Do you really want to do this?' which I'd prefer I think.

I guess I'm just afraid of accidentally overwriting my current ratings because of some bug. Restoring all of them to their original values would be too much work. I did notice the star backup files, though...

----
After importing FMPS_Ratings it doesn't seem to be possible to change the ratings? They automatically reset to FMPS_Ratings. Is this intended? (Haven't updated, yet)

**Comment by Taiko2k** [comment]
> After importing FMPS_Ratings it doesn't seem to be possible to change the ratings? They automatically reset to FMPS_Ratings. Is this intended?

Sounds like a bug. Maybe update to latest so we're on the same page.

**Comment by StrangeSeasOfThought** [comment]
> Sounds like a bug. Maybe update to latest so we're on the same page.
Done. Seems to be working now.

**Comment by StrangeSeasOfThought** [comment]
What about auto-rating album ratings like mentioned above? Average album tracks ratings = album rating.

**Comment by StrangeSeasOfThought** [comment]
Crash: When clearing all loved tracks.

**Comment by Taiko2k** [comment]
> Crash: When clearing all loved tracks.

OK fixed

**Comment by StrangeSeasOfThought** [comment]
> > Crash: When clearing all loved tracks.
> 
> OK fixed

python3 /opt/tauon-music-box/tauon.py %U
  File "/opt/tauon-music-box/tauon.py", line 18918
    if not key_focused and message_box_min_timer.get() > 0.4:
    ^
IndentationError: expected an indented block

**Comment by Taiko2k** [comment]
> What about auto-rating album ratings? 

I feel like this doesn't really add any meaningful information you can't already infer from looking at the track ratings (and the user would have to rate all tracks for this to begin to be meaningful). I think this would just introduce bias...and art can be more or less than the sum of its parts :wink:

**Comment by Taiko2k** [comment]
Ill close this now. Just create a new issue for any further issues
