### ISSUE TITLE
Datetime format

### ISSUE THREAD

**Issue by C0rn3j** [Taiko2k/TauonMusicBox#151]
![image](https://user-images.githubusercontent.com/1641362/62086938-3ce8b900-b260-11e9-9f52-3899eee6ea94.png)

Currently Tauon uses `YYYY-DD-MM`.

There's arguments for using `DD-MM-YYYY` over `MM-DD-YYYY`, but `YYYY-DD-MM` is not a recognized date format.

Switch to the standard [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format(`YYYY-MM-DD`) please.

**Comment by Taiko2k** [comment]
Can I ask what file format those tracks are? MP3 I assume?

**Comment by C0rn3j** [comment]
Yes.

Example song - https://cloud2.rys.pw/s/FZEwd6rgyZBNKCM

![image](https://user-images.githubusercontent.com/1641362/62087416-ee3c1e80-b261-11e9-8aaa-a9ac55e7efd2.png)

**Comment by Taiko2k** [comment]
The date displays in Tauon, for the most part, are shown exactly as they are read from the tags, so this would either be an issue with the tag reader, or the actual data in the tag is invalid. Since this shows correctly in other players, it would seem to be the former.

Tauon uses the library [Stagger](https://github.com/staggerpkg/stagger) to read ID3 tags. In inspecting that file you gave me, I see that the tag format is ID3v2.3. Looking in a hex editor reveals that the date and month components are stored in the frame named **TDAT**. The spec for that frame says this:

>**TDAT**
>The 'Date' frame is a numeric string in the DDMM format containing the date for the recording. 

And the date parsing code in Stagger for ID3v2.3 is this: https://github.com/staggerpkg/stagger/blob/6530db14afc5d7d8a4599b7f3b26158fb367d786/stagger/tags.py#L475. So it would seem Stagger got that around the wrong way, assuming MMDD instead of the actual DDMM.

Hmm, unfortunately that project seems to have been inactive for a couple of years now, so I doubt a pull request would go through. Ill just have to use a custom fork.

**Comment by C0rn3j** [comment]
Looks like one of the collaborators (lorentey) is active on Github in general, a PR just might go through.

**Comment by Taiko2k** [comment]
OK done. And Ill keep the workaround in Tauon for the next release.

**Comment by C0rn3j** [comment]
"tag rescan required to fix for existing tracks"

Took me a while to figure out how to do this. CTRL+A to select all songs in a playlist, Right click -> Reload metadata.

Thanks a lot for fixing this!

**Comment by Taiko2k** [comment]
I suppose you could do that. The intended way is right click playlist tab > misc... > rescan tags
