### ISSUE TITLE
I Love Taoun but don't like Flatpak 

### ISSUE THREAD

**Issue by emipta** [Taiko2k/TauonMusicBox#153]
i follow you're project since Tauon 2.6 version, today you're work is with flatpak .. 

i think not is secure use this platforma, is possible compile Tauon in *.appimage or other solution? 

Best regards, and apologises for Eng.

**Comment by Taiko2k** [comment]
I do also maintain an AUR package, which I have no plans on ending. Though, I realise that does leave users of non-Arch based distros with more limited options. 

I imagine it is *possible* to create an appimage. But its not simple to do, and maintaining the existing three release channels is already time consuming.

You *could* perform a manual setup, I believe there are some users who run it this way, though it requires more maintenance if you wanted to update versions. I might be able to give some guidance with this if you tell me what distro you're using.

I don't really have any other solution that is convenient at the moment unfortunately.

**Comment by smaragdus** [comment]
Off-topic- I am just a dabbler in Linux and I am curious- what is wrong with Flatpak and what are the advantages of AppImage?

**Comment by Taiko2k** [comment]
@smaragdus I don't think there is anything particularly wrong with Flatpak myself.

Perhaps one unique point of Flatpak is that packages and runtimes are built/compiled by Flathub, not the original developer, which means you have another party in the chain of trust. On the other hand, you don't need to trust the original developer as much as the build script is public (so would be much harder for the developer to hide malicious code).

I don't think AppImage has any particular advantages, apart from not needing extra software to install, it runs kind of like a plain `.exe` on Windows would. You have to download them manually and you don't get a *store* ecosystem. Its an advantage or disadvantage depending on how you look at it. This paradigm would be very familiar to Windows users, but I'm not sure its better.

One of the things I think is good about Flatpak is it has the best security sandboxing by default. Needing access to X11 is kind of a security hole at the moment, but once Wayland is better supported, apps will be very limited in damage they can potentially do, even if they were malicious.

**Comment by smaragdus** [comment]
@Taiko2k 

Thank you very much for the informative post. For Linux novices like me it seems that AppImage is the better and easier choice.

**Comment by Taiko2k** [comment]
@smaragdus The ideal of Flatpak is that it would be as easy as it is on Andorid/iOS, one click to install, and you can manage and uninstall apps from a single place, leave reviews etc. 

Its just slightly more involved at the moment since not all distro's have it installed by default, and software managers like Gnome Software need a bit of work to really smooth the user experience, and sandbox portals need improvement to make things like drag and drop work out the box.

**Comment by Solarunit** [comment]
I think flatpak is nice, I prefer it over snaps (I had a bad experience with snaps and I don't like loop devices it creates)

Sometimes Tauon flatpak doesn't start because of the system updates (nvidia drivers or new kernel)
Well I am using a rolling system (Solus)

So after updates I have to do `flatpak update` in the terminal. Not a big problem because it starts every time after that =)
