### ISSUE TITLE
Song title text is hidden weirdly

### ISSUE THREAD

**Issue by Bauke** [Taiko2k/TauonMusicBox#175]
So the text here that shows the playing song gets hidden very quickly even though there's plenty of space for it.

Visible, with a pretty large width:

![image](https://user-images.githubusercontent.com/19501722/65405785-de0d6f00-ddcc-11e9-84f5-8162bc314079.png)

Hidden, only a slightly smaller width:

![image](https://user-images.githubusercontent.com/19501722/65405806-f7162000-ddcc-11e9-9430-9d1b766e15d9.png)

I also noticed this seems to be dependent on the width of the "main" area with all the tracks, since if I resize the sidebar with the album cover and lyrics to be bigger (and the main area to be smaller) it will become visible again.

**Comment by Taiko2k** [comment]
Its currently intended to hide if there's room for the text in the side panel, in order to reduce redundant information. I assume that's what you're seeing.

**Comment by StrangeSeasOfThought** [comment]
I don't think it's redundant information in this case. Actually, it's pretty useful because you can find out the most important information (artist - title) with just a glance and it's close to the play buttons, so I don't have to move my eyes away, upwards (playlist) or to the right side panel when changing tracks and so on.
If I want more information like artwork, album, release date, genre I can look at the sidebar.
It'd also be consistent throughout the app (compact layout excluded) to always find artist - title at the same place, no matter playlist position or right sidepanel view.

**Comment by Taiko2k** [comment]
I prefer the current behavior, myself.

I'll add this as an optional setting.
![Screenshot from 2019-09-23 23-14-36](https://user-images.githubusercontent.com/17271572/65421500-fb3b4f80-de57-11e9-8fcd-0426824a4c59.png)

**Comment by Solarunit** [comment]
@Bauke what kind of theme it is?

![alt text](https://user-images.githubusercontent.com/19501722/65405806-f7162000-ddcc-11e9-9430-9d1b766e15d9.png)

**Comment by Taiko2k** [comment]
BTW, you can place custom themes in the user data folder inside a folder named `theme`. I should probably document this somewhere and have this folder auto-created.
