### ISSUE TITLE
Lyrics icon next to the love hearts

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#191]
There is a lyrics button in the right panel but its always hidden if you are using the full album cover or centered style cover. So the idea is to add the lyrics icon :notes:  next to the love hearts in the playlist as an option.

Another idea - hotkey to show/hide lyrics in the Showcase view. And maybe hotkey to open lyrics in the Showcase view from the Tracks+Art view. Maybe it will be the same hotkey.

F6 (it activates Now streaming for me, but it is Reserved according to wiki)
Ctrl+F5
Ctrl+L

**Comment by Taiko2k** [comment]
Yeah the lyrics switching is a bit messy at the moment.

I'm not *suuure* if a lyrics button should go next to the love hearts though, cause together with playtime lines or stars, it makes the alignment kind of weird. There can be not much room, so I think this area should at least only show the same type of information, playcount/like/stars etc.

Unless a lyric button could go at the end to the track title... still a little weird looking perhaps.

I feel like there should also be an easier way to switch/toggle lyrics in the side panel too, but I'm not sure where such a button should go either.

> And maybe hotkey to open lyrics in the Showcase view from the Tracks+Art view.

Ctrl+L sounds like a good idea I think.

**Comment by StrangeSeasOfThought** [comment]
> So the idea is to add the lyrics icon  next to the love hearts in the playlist as an option.

Why not use columns instead? There's a column for lyrics.

**Comment by Taiko2k** [comment]
@StrangeSeasOfThought They're currently not clickable as a shortcut, but could make them so.

**Comment by StrangeSeasOfThought** [comment]
Oh, it's supposed to toggle lyrics (I don't use them)? Why not add it to the bottom panel then? It'd fit there nicely, imo.

- no lyrics: no button
- has lyrics, show button: mode on color
- has lyrics, show button: mode off color

**Comment by Taiko2k** [comment]
@StrangeSeasOfThought Yeah that idea came to mind also. Have it toggle lyrics in the side panel, and remove the confusing `Hide art box` / `Show/Hide lyrics` options

**Comment by Solarunit** [comment]
> I'm not _suuure_ if a lyrics button should go next to the love hearts though, cause together with playtime lines or stars, it makes the alignment kind of weird. There can be not much room, so I think this area should at least only show the same type of information, playcount/like/stars etc.

Its not a button but a small indicator like this :notes: 
You can't click on it.

> I feel like there should also be an easier way to switch/toggle lyrics in the side panel too, but I'm not sure where such a button should go either.

>This will remove the availability of lyrics under the album art, though I don't think that feature ever really made a lot of practical sense.

Do you mean to add some button in the right panel somewhere (maybe hidden) to open lyrics in the Showcase view? And remove the lyrics from the right panel?
I think it makes sense because lyrics looks better in the Showcase view.

**Comment by Solarunit** [comment]
> Why not use columns instead? There's a column for lyrics.

I prefer the minimal playlist and not a table view.

**Comment by Taiko2k** [comment]
> but a small indicator

Even still, I don't think there is room. Next to the hearts would look messy since it wont align and isn't the same type of information.

> Do you mean to add some button in the right panel somewhere (maybe hidden) to open lyrics in the Showcase view? And remove the lyrics from the right panel?

Actually I was thinking of having it in the bottom panel, and clicking it going to the right panel and not the showcase. Though, I hesitate since I don't want to risk cluttering the bottom panel, and there's no room as it is in the compact layout.

**Comment by StrangeSeasOfThought** [comment]
> and there's no room as it is in the compact layout.

Well, you could decrease the width of repeat and shuffle buttons, they're kinda oversized for compact, imo. You could even enforce xx:xx instead of xx:xx / xx:xx to gain even more space.

**Comment by Solarunit** [comment]
>Next to the hearts would look messy since it wont align and isn't the same type of information.

Yeah maybe a little messy, I agree. I am using only love tracks feature.

**Comment by Solarunit** [comment]
@StrangeSeasOfThought the button looks very different from the rest

**Comment by StrangeSeasOfThought** [comment]
It's just a placeholder.

**Comment by Taiko2k** [comment]
I'm not really feeling the bottom lyrics button idea. Adds to the clutter and maybe isn't the right way to solve the problem. Though I do think there are some immediate issues with how lyrics work in the side panel.

Here's something I've been working on. Once enabled, whenever a playing track has lyrics, the side panel automatically shows this alternate layout.

![Screenshot from 2019-11-05 23-25-52](https://user-images.githubusercontent.com/17271572/68201316-6ca91900-0026-11ea-856a-e3a4d80cf8d8.png)

So, now there's no information missing by showing lyrics, and doesn't require user intervention. 

As for the original issue, I think im gonna go with wontfix for this, since I don't think there's any space that doesn't aesthetically interrupt any other element without using columns.
