### ISSUE TITLE
[Flatpak][CloudReady Chrome OS] No data

### ISSUE THREAD

**Issue by SnnTsukiEXE** [Taiko2k/TauonMusicBox#206]
I have installed the app, and It look great, but It doesn't open data folder, or config file, I tried to use **--filesystem=home** but nothing happened, same problem, I tried to open with **sudo flatpak run com.github.taiko2k.tauonmb** and It send this:

![Screenshot 2019-11-16 at 18 27 41](https://user-images.githubusercontent.com/54377769/68996774-01b9d680-089f-11ea-9a1a-c71cc50984bb.png)

¿It's posible to fix it?

(PD: it strangely loads with Dolphin File Manager but even with this i cant open folder for the app)

**Comment by Taiko2k** [comment]
The error shown seems unrelated. I think it's because you tried running as root, so, try not use sudo when running.

Try test opening a folder using command xdg-open, like `xdg-open ~/Documents` and see if that works.

Regardless, you should be able to manually find the data and config directorys at `~/.var/app/com.github.taiko2k.tauonmb/`
