### ISSUE TITLE
[Enhancement] Restrict network access via settings

### ISSUE THREAD

**Issue by lakrivit** [Taiko2k/TauonMusicBox#223]
Having a toggle in settings, allowing/ restricting network access for sending track metadata, starting a broadcast etc. would be a great privacy friendly option.

Currently Tauon automatically starts looking for album covers and artist information online when viewing the artist list panel and artist info panel.

Would be great to restrict this behaviour so you don't accidentally start fetching all this information online.

**Comment by Taiko2k** [comment]
Yes I think there should be better control over those elements that operate automatically. Perhaps a setting named "Enable automatic fetching of artist data". Set to disabled by default even.

I'm unsure if any other non automatic functions should be included. The "Start Broadcast" function in particular requires an incoming connection before any data is sent out, which is unlikely to occur unintentionally.

**Comment by lakrivit** [comment]
That sounds good to me :)

Other non-authomatic functions would perhaps be the `Show in context menus` options. Having these, `Search artist on Wikipedia`, `Show playing in Discord` etc., greyed out if `Enable automatic fetching of artist data` is set is probably the easiest solution.

**Comment by Taiko2k** [comment]
Ive pushed a change now. This change now allows manual triggering of data download in the artist bio panel when automatic has is disabled.

___

As for other functions, I think the user can be careful enough not to click them unintentionally... and most of them can be disabled in some way.

I can kind of see the appeal of a "Disable all network activity" setting, though I hesitate to because don't want to imply such a feature would be reliable. Also debatable as to if those search on website entries should fall under that. Could lead to user confusion.

**Comment by Taiko2k** [comment]
Latest release should have the mentioned change now.
