### ISSUE TITLE
Change ''appdata.xml'' according to latest Flatpak documentation

### ISSUE THREAD

**Issue by DesertStars** [Taiko2k/TauonMusicBox#227]
Hi, first thanks for making this great software, it's my favorite music player so far among the ones I've used. 

I noticed that in [appdata.xml](https://github.com/Taiko2k/TauonMusicBox/blob/master/extra/com.github.taiko2k.tauonmb.appdata.xml) id is `com.github.taiko2k.tauonmb.desktop` which doesn't suit to [Expected Standards in Flatpak Documentation](https://github.com/flatpak/flatpak-docs/blob/master/docs/conventions.rst#expected-standards), according to that `.desktop` should removed and `.com` should be changed to `.io.`.

So it'd be `io.github.taiko2k.tauonmb`.

**Comment by Taiko2k** [comment]
Yes that does seem to be a mistake with the desktop bit, must have mistaked it for the desktop-id field.

As for `io.` or `com.`, I've seen apps use either. 
I chose com because the io url currently 404s, there's no website setup. It would be too difficult to change the ID now since it's used by Flathub.

**Comment by DesertStars** [comment]
True, I see your point. It's kinda weird to use `.io` even for software without a Github Page. I thought you've missed that, if it's a deliberate decision it's only `.desktop` then.
