### ISSUE TITLE
View1 and View2 in the Settings

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#250]
I think it's a little bit confusing to have two Views in the settings.

**Comment by Taiko2k** [comment]
I agree this isn't ideal.

The issue was, having the two column style didn't allow horizontal room for translations. I'm open to ideas and concepts for improving the setting layout.

Might just have to increase the vertical height of settings box. Probably the best solution. I had liked the current shape, and it worked well with small windows, but oh well. 

Putting in scroll bars is a possibility, though I'm not sure I'm feeling thats a great idea.

**Comment by Taiko2k** [comment]
For now I've just changed one of these to "Window"
