### ISSUE TITLE
[Feature Request] Support of webradios (PLS, ASX etc)

### ISSUE THREAD

**Issue by awsms** [Taiko2k/TauonMusicBox#259]
Would it be possible to import typical webradio stream files (.pls .m3u) files on Tauon?
Also, if these radios give metadatas for each song broadcasted (artistname, songname) to scrobble them? :D

**Comment by Taiko2k** [comment]
Indeed there is room for improvement with the existing radio function, such as being able to import .pls files. Internet radio seemed kind of outdated to me so I hadn't given it priority. But I can work on it if there's demand.

I'll probably only do .pls though since its by far most common.

Note that you *can* currently play internet radio if you extract the URL manually and paste it into the "Open Stream..." box. (Only working with BASS backend)

**Comment by Taiko2k** [comment]
OK I've got some changes. Last.fm scrobbling for radio should be working. Also you can now drag and drop or *open with* PLS and M3U files to import stations to the internet radio box list. 

> Though there's an issue using *open with* from a web browser with snap. Does seem to work when using *open with* with a file browser though.

If you like, you could try out the latest dev build and know what you think so far.

 1. `snap switch --channel=edge tauon`
 2. `snap refresh`
You can switch back with:
 1. `snap switch --channel=edge tauon`

Maybe make a backup of your user data folder just in case since I don't fully guarantee downgrade-ability or upgrade-ability from a dev version.

**Comment by Taiko2k** [comment]
This should be live in the latest release now. 

As I mentioned before, there may be an issue opening from some web browsers with the snap version. (I think it might be a permission issue when the browser tries to open the playlist file from a temporary location.)

**Comment by gerroon** [comment]
> OK I've got some changes. Last.fm scrobbling for radio should be working. Also you can now drag and drop or _open with_ PLS and M3U files to import stations to the internet radio box list

Hi I think that this functionality is not working with drag and drop. Here is a .m3u file that I drag anbd drop to Tauon, and all I get is an empty "New Playlist", nothing in it.

I am usinf the Flathub version v.6.5.4 and I already setup file access with

`sudo flatpak override com.github.taiko2k.tauonmb --filesystem=host`

test.m3u
```
http://ice1.somafm.com/doomed-128-mp3
http://ice3.somafm.com/dronezone-128-mp3
http://ice2.somafm.com/dronezone-32-aac
http://ice1.somafm.com/cliqhop-128-mp3
http://ice2.somafm.com/defcon-128-mp3
http://ice1.somafm.com/dubstep-128-mp3
http://ice1.somafm.com/earwaves-128-mp3
http://ice1.somafm.com/missioncontrol-128-mp3
http://ice1.somafm.com/sonicuniverse-192-mp3
http://ice1.somafm.com/spacestation-128-aac
http://ice1.somafm.com/silent-128-mp3
http://ice1.somafm.com/sf1033-128-mp3
http://ice.somafm.com/secretagent


```

**Comment by Taiko2k** [comment]
@gerroon Check under MENU > Internet Radio. Stations only go there and not to the playlists.

It creating a blank playlist when you drag n drop is a known quirk.

**Comment by gerroon** [comment]
> @gerroon Check under MENU > Internet Radio. Stations only go there and not to the playlists.
> 
> It creating a blank playlist when you drag n drop is a known quirk.

Ahh, now I see how this supposed to work. Thanks for the pointing it out.
