### ISSUE TITLE
Windows releases

### ISSUE THREAD

**Issue by emipta** [Taiko2k/TauonMusicBox#290]
Please is possible compile last version for Windows ¿please?  .. 

Love Tauon Music Box, love you're work..  :)

**Comment by Taiko2k** [comment]
Unfortunately the codebase is diverging and maintaining the old Windows compatibility has become dismal. However... there is another way... 

I've put in some changes now for a new way of running under Windows. This involves setting up a development like environment to which you could run Tauon from.

Benefits of the new way:
 - You get more or less all the features that the Linux version has.
 - You can update whenever you want, you don't have to wait for me to make a package.

Downsides:
 - You'll have to follow some instructions to install it, and the install size is pretty large.
 - File associations wont work. Also the taskbar progress feature wont work any more.
 - Possible other bugs and quirks.

___
### How to:

1. Go to http://www.msys2.org/ and download the one click installer, and install it with the defaults.
2. Go to and run C:\msys64\mingw64.exe
3. In the terminal window that pops up,  run (choose Y when prompted):
   >  pacman -Syu
4. Once thats done, close the window, then repeat steps **2** and **3** again.
5. In that same window run:
   > pacman -S mingw-w64-x86_64-gtk3 mingw-w64-x86_64-python3 mingw-w64-x86_64-python3-gobject mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_image mingw-w64-x86_64-python-pip mingw-w64-x86_64-python-pillow mingw-w64-x86_64-python-comtypes
6. Now run:
   > pip install -r c:/msys64/TauonMusicBox/extra/requirements-windows.txt
7. Download the zip file of this repo, and extract the `TauonMusicBox` folder to `c:\msys64` so that it now looks like `c:\msys64\TauonMusicBox`.
8. Download https://github.com/Taiko2k/TauonMusicBox/releases/download/v5.5.3/win-basslibs.zip and extract the `lib` folder to `c:\msys64\TauonMusicBox` so that it now looks like  `c:\msys64\TauonMusicBox\lib`
9. Right click on your desktop and create a new shortcut. Enter the target as:
   >  C:\msys64\usr\bin\mintty.exe -w hide /bin/env MSYSTEM=MINGW64 /bin/bash -lc C:/msys64/TauonMusicBox/extra/win-run.sh
10. Now when you want to run, you just double click that shortcut.

I think that should work. Though there might be bugs or steps I missed. Let me know how that goes.

Bugs:
 - Transcoding might not be working yet.
 - Open tag editor probably wont work yet.

It may be possible to package this into an easy installer like it used to be. But that's a fair bit more work.

**Comment by Taiko2k** [comment]
Okay I've compiled a simple installer. Note this is very beta and some things aren't working.

I recommend uninstalling the previous Tauon Music Box first. Keep the old installer around and **backup** your TauonMusicBox folder! (in Music) in case you want to go back.

https://github.com/Taiko2k/TauonMusicBox/releases/download/v5.5.3/tauon-setup64-v5.5.5-testing-1.exe

Known issues:
 - Media keys not working
 - Last.fm not working

**Comment by emipta** [comment]
thanks a LoT Taiko!! :)     ...  love this player! ..

**Comment by emipta** [comment]
Not is possible put on allscreen and not recognice japanese Kanki! ..   see picture. 

<img width="1775" alt="Sin título" src="https://user-images.githubusercontent.com/37155732/82765864-c6cec780-9e1a-11ea-92b4-2bc3ff61eec7.png">

**Comment by Taiko2k** [comment]
I'm having a bit of trouble with the fonts. I'm not sure why its not working properly. See if this one works better. The font isn't quite right but at least its showing Kanji for me:

https://github.com/Taiko2k/TauonMusicBox/releases/download/v5.5.3/tauon-setup64-v5.5.5-testing-4.exe

As for the maximising thing, I'm getting this issue on too,  but I don't currently have a solution.

**Comment by emipta** [comment]
No problem, you're work is amazing!!!!!     ( ´ ∀ `)ノ～ ♡

Thanks a lot again ... 

いいんですよ、あなたの仕事は素晴らしいですよ！！！！！！！（笑

本当にありがとうございました

**Comment by Taiko2k** [comment]
はいはい、我慢しってた。
