### ISSUE TITLE
mint-y-dark themes

### ISSUE THREAD

**Issue by tranzzzistor** [Taiko2k/TauonMusicBox#291]
If you'd like, I've created 11 user themes that match the 11 "mint-y-dark" gtk themes present in Linux Mint 19.3 and I'd be happy to share them.

(mint-y-dark, mint-y-dark-aqua, mint-y-dark-blue, mint-y-dark-brown, mint-y-dark-grey, mint-y-dark-orange, mint-y-dark-pink, mint-y-dark-purple, mint-y-dark-red, mint-y-dark-sand and mint-y-dark-teal)

**Comment by Taiko2k** [comment]
Ill be interested to take a look! (If you need a place to upload them you can just zip them and attach to your comment here).

**Comment by tranzzzistor** [comment]
ok, here they are :)
[tauonmb-mint-y-dark-themes.zip](https://github.com/Taiko2k/TauonMusicBox/files/4709230/tauonmb-mint-y-dark-themes.zip)

**Comment by Taiko2k** [comment]
Interesting. I should at some point publish a list of themes people have made, maybe on the website somewhere.

To comment on the theme, it seems good, though just a few things I noticed:

 - I feel like the contrast between the panel backgrounds needs better balancing. Mainly the gallery/side backgrounds, I actually like the strong contrast there but IDK if it fits with the intent of your theme?

   ![Screenshot from 2020-06-01 15-34-25](https://user-images.githubusercontent.com/17271572/83373875-fafb4700-a41d-11ea-9cb3-9c2655461026.png)

   What I would probably try is use a darker grey for `side panel` that's closer to the gallery background (Gallery background is `gallery background`)

   Getting the balancing good is pretty hard, especially since one panel can be touching up to 3 others.

   (BTW the theme `sunken.ttheme` actually currently has the most entries listed, mostly for things like the dialogue box colours, if you wanna get more advanced.)


 - The contrast of the seek/volume background seems low to me.
 - The contrast of the context menu background seems low to me.

**Comment by tranzzzistor** [comment]
You're right about it being hard to get the balance right; however I find the lower contrast best for viewing, especially since I'm always reading lyrics in the side panel. One of the reasons I really like the mint-y-dark gtk theme itself is that it's more of a dark grey theme than a black or dark blue.
YMMV of course. 
It would be cool if you did add a section to the website :)

**Comment by tranzzzistor** [comment]
I do agree about the seek/volume backgrounds being too low. I hadn't actually noticed those before, but you're right. I've modified 
[tauonmb-mint-y-dark-themes-Rev1.zip](https://github.com/Taiko2k/TauonMusicBox/files/4709524/tauonmb-mint-y-dark-themes-Rev1.zip)

**Comment by Taiko2k** [comment]
I've added a section for themes in the site now https://taiko2k.github.io/tauonmb-site/#themes

**Comment by tranzzzistor** [comment]
nice! :)
