### ISSUE TITLE
Guayadeque

### ISSUE THREAD

**Issue by ben2talk** [Taiko2k/TauonMusicBox#293]
The ability to do smart play with filtering would make this a good jukebox - like Guayadeque.

**Comment by Taiko2k** [comment]
Could you explain in more detail what this feature does? Could you give an example use case?

**Comment by Taiko2k** [comment]
Okay I found some Guayadeque documentation.

> In practice what the Smart Mode allows you to do is create your own Radio Streams with your whole library as its raw material. The main difference with playing your playlists directly is that it adds another filtering layer (the deny filter) and that
you don't decide or know what track/tracks come next. You can be as specific or unspecific as you want: allow all and deny none to let Guayadeque randomly stream your entire collection; or allow for example dance music from the seventies but deny any tracks played more than twice in the last month.

I think this is mostly covered by the existing "**Generator playlists**" feature of Tauon. To implement that given example in Tauon, the code would be: `g"dance" y>=1970 y<1980 pc<2 rt`, though there is a slight difference in that Tauon doesn't keep track of when a track was played so can't constrain to the 2 weeks.

I also notice references to last.fm for deciding what tracks are added. I will go with wontfix for that because I don't want any further dependency on last.fm, I feel it is too great as it is.
