### ISSUE TITLE
Preffer file cover over embedded in display order

### ISSUE THREAD

**Issue by C0rn3j** [Taiko2k/TauonMusicBox#30]
Some music has embedded covers.

I don't have a large music collection so the following is an assumption - file covers will practically always be higher quality as the embedded covers will usually try to remain small, or at least they will be identical quality than a file cover if present and not better.

As it is right now, embedded is displayed first over file cover.

![image](https://user-images.githubusercontent.com/1641362/52330912-fc1d8f00-29f6-11e9-8f23-50b17ba0f48b.png) ![image](https://user-images.githubusercontent.com/1641362/52330925-05a6f700-29f7-11e9-94f9-37e95a6e6fea.png)

**Comment by Taiko2k** [comment]
I see what you mean here...

Though on the other hand, the problem is that some albums have unique embedded art for each track which maybe would have higher priority than the file image.

Also taking a look at my library, its not awfully uncommon for the embed to be larger than the file, also the file is often a different/miscellaneous picture to that of the embedded cover art.

I think perhaps the solution should be on the user end to remove small embedded art like that. Also, once you do switch it, Tauon Music Box will remember that for the whole album even after restart, so once you've used the app for a while, it becomes less of an issue.

**Comment by C0rn3j** [comment]
I think that's fair. Either remove/redo the cover art on my side or switch to it myself.
I wasn't aware that such albums with unique per-song art + unique cover can exist, so I guess the current state works as well as it could.
