### ISSUE TITLE
Add button and shortcut for to maximize window

### ISSUE THREAD

**Issue by Porkepix** [Taiko2k/TauonMusicBox#315]
The software run by default in windowed mode, and only have buttons to minimize and quit. Have a button to maximize would be welcome. I also tried to double click the zone besides those buttons as this would be the window decoration zone in many software and that double clicking this would maximize/change to windowed mode the software.

**Comment by Taiko2k** [comment]
Unfortunately due to a limitation of the underlying SDL2 library, its not possible for a region to be both draggable and clickable :confused: 

I don't want to add a maximize button because I prefer to keep it minimal. Most window managers allow you to drag the window to the top of the screen to maximise which I find to be more fluid than clicking a button anyway.

I could perhaps add something a little more obscure like *right clicking* the minimize button to maximize, hows that sound?

**Comment by Porkepix** [comment]
> Unfortunately due to a limitation of the underlying SDL2 library, its not possible for a region to be both draggable and clickable confused
> 
> I don't want to add a maximize button because I prefer to keep it minimal. Most window managers allow you to drag the window to the top of the screen to maximise which I find to be more fluid than clicking a button anyway.
> 
> I could perhaps add something a little more obscure like _right clicking_ the minimize button to maximize, hows that sound?

It indeed does work with my current WM (Gnome), but I'm afraid it's not the case for all of them, especially I have in mind ones like XFCE or LXDE (I didn't ran them for a very long time so I can't be sure) that probably doesn't have such feature. And obscure ways of do so with some kind of hidden features might not be that nice for discoverability.

**Comment by Taiko2k** [comment]
Okay I've gone all out and added a maximize button. There's a new config setting to disable this if users prefer the old layout.

![Screenshot from 2020-07-25 20-15-31](https://user-images.githubusercontent.com/17271572/88452616-614b9580-ceb4-11ea-9a01-4211d85ac3f5.png)
