### ISSUE TITLE
[not a bug] Tauon makes polybar's transparent areas black

### ISSUE THREAD

**Issue by zSucrilhos** [Taiko2k/TauonMusicBox#323]
Hi! First of all i want to congratulate you all for the amazing piece of software, i can say that this one is one of the best looking GUI music players i've used in the past 10 years.

A problem i have as i am using bspwm and polybar is that in the desktop in which i open tauon (my case, 8, but it can be whatever desktop number, whatever) polybar's transparent areas turn black for some reason. I have it set in my polybar config like:
#00000000, so it is black, but transparent. I don't know what might be causing this but i can imagine that it is something related to Tauon's internal window managing system (i'm not programmer, tho, it's just a kick).

There is something that could be done to avoid this? I am using Tauon without the option *Settings > Window > Draw own window decorations* set. Thanks in advance!

![image](https://user-images.githubusercontent.com/37763819/88987610-e23bd000-d2ac-11ea-8e89-8034a480b2ee.png)

And here's a image of how it would be normally:
![image](https://user-images.githubusercontent.com/37763819/88987872-ad7c4880-d2ad-11ea-85ad-9cfa7606e57d.png)

**Comment by Taiko2k** [comment]
FYI Tauon uses SDL2 for its windowing.

I just did a test with polybar myself and it seems to be working as expected for me (I'm using mutter wm). So it could be due to some kind of interaction between bspwm and SDL2.

I see there was this issue here https://github.com/baskerville/bspwm/issues/375. While it doesn't sound like the same issue, it does establish a precedent for unexpected interaction with bspwm and SDL2.

I don't think there's an easy solution on my side. If you wish to pursue further, I might suggest creating a new issue on bspwm.

**Comment by zSucrilhos** [comment]
Alright, thanks for the support!

**Comment by Taiko2k** [comment]
Although annoying, this seems out of scope for me to fix unfortunately. Ill close this issue.
