### ISSUE TITLE
Feature request: Deezer

### ISSUE THREAD

**Issue by mannp** [Taiko2k/TauonMusicBox#344]
As a **better** (flac audio for the same or cheaper than spotify) :) I wondered if you had in your region and would consider some deezer functionality?

**Comment by Taiko2k** [comment]
Well *achtuaally* the FLAC Deezer plan costs more then standard Spotify. At least in my region. 

Anyway, I took a look. Deezer seem to have a more restrictive API. So its not really possible to play music without doing some gymnastics and skirting their terms of service. So that and me not using Deezer means I'm not interested in trying to add this. Sorry.

**Comment by mannp** [comment]
No problem, thanks for taking a look.
