### ISSUE TITLE
Menu button is moving when you add new playlists

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#35]
Menu button is moving when you add new playlists.

**Comment by Taiko2k** [comment]
That's the design, for better or worse. I tried having the menu button on the right side of the tabs but it didn't feel right to be, perhaps because I was used to it on the left or didn't look nice to me.

I *could* add a setting for this, but if you'd rather have the tabs disabled entirely, perhaps we could just go with a setting for that?

**Comment by Solarunit** [comment]
If there will be setting to disable horizontals tabs, I think it's fine. 
But for those who use these tabs the floating menu will looks strange ) 

----

BTW Do you plan to add scrolling tab feature when there are many playlists opened? Firefox-like tabs scrolling.

**Comment by Taiko2k** [comment]
No. I guess it is a bit awkward having them simply truncated, but I think having them scrollable like that might be getting a bit convoluted, I think the idea I was going for is If you have many tabs, is to just 'unpin' the ones you're not using.

**Comment by Solarunit** [comment]
> I think the idea I was going for is If you have many tabs, is to just 'unpin' the ones you're not using.

or just use playlist panel
