### ISSUE TITLE
[Feature Request] Option to disable horizontal playlists

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#36]
I think there should be an option to disable horizontal playlists.

**Comment by Taiko2k** [comment]
I've added this. I've decided for now to merge #37 with this feature since having multiple indicators looks cluttered. Will see how this goes.

I haven't bummed the version yet, but this change is live on the latest Flatpak (now moved to Flathub). 

___

If you want to upgrade here is the procedure:

Uninstall the old package:
   `sudo flatpak uninstall com.github.taiko2k.tauonmb`

Install flathub version:
`flatpak install flathub com.github.taiko2k.tauonmb`

then from now updates can be done by running: `flatpak update`

**Comment by Solarunit** [comment]
> I've added this. I've decided for now to merge #37 with this feature since having multiple indicators looks cluttered. Will see how this goes.

I like it! Thanks!
