### ISSUE TITLE
[Feature Request] Use standard previous/next track controls

### ISSUE THREAD

**Issue by dspacejs** [Taiko2k/TauonMusicBox#360]
As a user, I expect that clicking the previous button will take me to start of the current track, instead of the previous track in the queue. If I want the previous track in the queue, you should click the previous track button twice.

I also expect that if a song is on repeat, clicking the "next" button should take me to the beginning of the same track (instead of whatever is next in the queue). 

This is the standard behaviour of every music app I've used, so it's confusing if this one doesn't do the same thing.

P.S nice work, this is the first decent Linux music player I've found.

**Comment by Taiko2k** [comment]
The current behavior of the playback controls is very intentional. 

I believe its the preferred/correct behavior. My reasoning is that most of the time when one presses *back*, they want to go to the previous track, so that function should be the primary. Its also the more predictable behavior since it isn't based on any timings.

In Tauon, if one wants to go to the start of the song, you can click the seek bar, or press *back* and *froward* in quick succession.

If repeat is on, I don't see changing the behavior of the playback controls is necessary. If you want to restart the track you can use the above method, leaving the primary function of the *next* button as its original purpose which is more consistent.

Its the behavior existing users of Tauon will be familar with. I think there could be an argument for adding settings for this, though settings add clutter and complexity, so I would prefer to avoid them.

**Comment by dspacejs** [comment]
@Taiko2k I think a setting for this would be worth it. Just a simple checkbox. Would give people the ability to choose whatever they prefer, I assume many users would be like myself.

**Comment by Solarunit** [comment]
>This is the standard behaviour of every music app I've used, so it's confusing if this one doesn't do the same thing.

I think that described behavior is also confusing...
The current behavior is ok.

>In Tauon, if one wants to go to the start of the song, you can click the seek bar, or press back and froward in quick succession.

I just use double click or hit the Enter =)

>P.S nice work, this is the first decent Linux music player I've found.

Agree, Tauon is awesome, so thanks again @Taiko2k  :+1:

**Comment by awsms** [comment]
I perfectly see what dspacejs describes here, I developped the habit to quickly press "previous" then "next" to go back at the beginning of a track in tauon.
I've already considered about opening an issue for adding a "go-to-track-beginning" key in the keymap file, but that would be annoying to have two different keybinds (beginning of a track, and previous track) for two functions that should be the same imo.

**Comment by awsms** [comment]
I perfectly see what dspacejs describes here, I developped the habit to quickly press "previous" then "next" to go back at the beginning of a track in tauon.
I've already considered about opening an issue for adding a "go-to-track-beginning" key in the keymap file, but that would be annoying to have two different keybinds (beginning of a track, and previous track) for two functions that should be the same imo.
However, a tickable option in the settings to change this behaviour would be a good compromise.

**Comment by Taiko2k** [comment]
Okay I've added a setting to the config file called `back-restarts`. Let me know if its behavior is satisfactory.

**Comment by dspacejs** [comment]
@Taiko2k how do I test it? I've been trying `flatpak update` but there has been no releases for Tauon recently

**Comment by Taiko2k** [comment]
@dspacejs Oh, you would have to setup from git, but never mind, probably easier to just wait until next stable release.

**Comment by Taiko2k** [comment]
Okay this should be live (v6.3.3), look for `back-restarts` in the config file.

**Comment by dspacejs** [comment]
I actually prefer your configuration after trying both. Good idea.
