### ISSUE TITLE
[Feature Request] Show the progression of an Airsonic library scan

### ISSUE THREAD

**Issue by awsms** [Taiko2k/TauonMusicBox#389]
Could it be possible to add a progressbar in the GUI, or even show the current scanned files in the CLI output?

**Comment by Taiko2k** [comment]
I can add a counter in the UI that counts the tracks imported so far, though I don't think a progress bar is possible since I don't see a way of totalling the tracks beforehand.

Here's what I got:

![Screenshot from 2020-10-02 12-58-11-cropped](https://user-images.githubusercontent.com/17271572/94874709-274bd080-04af-11eb-8c36-275265128743.jpg)

**Comment by awsms** [comment]
Thanks! It was more a way of debugging and figure out if the scan is actually happening than having an exact idea of the scan progression.
When you have several terabytes of data and it can take hours to scan, it's quite frustrating to figure out couple hours later that Tauon wasn't scanning anything.
I can see the total number of tracks stored in a db file, but I don't know how to make an API call to get this value.
