### ISSUE TITLE
Weird Japanese character behavior in Mint

### ISSUE THREAD

**Issue by Tyrannidae** [Taiko2k/TauonMusicBox#398]
Songs with Japanese characters don't show up correctly in the tracklist, but they show alright in the left and right panels.

Appears to be exclusive to hiragana and katakana characters (didn't fully test this).
Fonts-noto-cjk and Fonts-noto-cjk-extra are already installed.
Issue remains with either Flatpak or Snap.

This seems to only happen in Linux Mint systems.

**Comment by Taiko2k** [comment]
I did a test with a fresh Linux Mint 20 Cinnamon in a VM, and it seems to be working fine... so, huh.

I think it might have something to do with the fonts you *have* installed, not necessarily fonts you're missing.

On further examination I find that although the CJK fonts are bundled... currently their use isn't being forced, its just whatever the default fontconfig decides, which is a little inconsistent. For example here's how the fonts are resolving on my system:

 - Noto Sans -> IPAGothic
 - Noto Sans Bold -> Noto Sans CJK JP

So that would be consistent with the difference you're seeing. The bold font tends to resolve correctly but the normal one doesn't for some reason.

What to do... what to do....

Here's an experiment, we can try force the use of the font. Try open Tauon config file (You can press `Open config file` in settings), edit the font settings under `[fonts]` to this

> font-main-standard = "Noto Sans, Noto Sans CJK JP"
> font-main-medium = "Noto Sans Medium, Noto Sans CJK JP Medium" 
> font-main-bold = "Noto Sans Bold, Noto Sans CJK JP Bold"

Then press `Reload` (Or save the file with Tauon closed). Then start again and see if that works.

**Comment by Tyrannidae** [comment]
Sorry for the delay!
