### ISSUE TITLE
Gallery view doesn't focus album art on shuffled track change

### ISSUE THREAD

**Issue by dwestford17** [Taiko2k/TauonMusicBox#426]
When shuffling tracks, the gallery view isn't updated/scrolled to highlight the new album art. To recreate this simply play a song with the gallery view and shuffle active, fast forward to the end to let the song end and another track begin. Every other view is updated to the new track but the gallery view is not. When skipping tracks normally, this isn't an issue. Letting multiple albums play through normally also doesn't focus/scroll to the new album art. 

See attached screenshot for reference. 
![Screenshot from 2020-12-04 09-16-05](https://user-images.githubusercontent.com/65442684/101168193-75956100-3611-11eb-805c-163f1129ab67.png)

**Comment by Taiko2k** [comment]
This behavior is actually intentional. Its intended that you use "go to playing" to set the view to the track.

I don't have solid reasoning for this apart from it being what felt better to me. The main issue essentially is running into a situation where the view is yanked while you're trying to browse elsewhere and a track happens to transition. (While this can currently happen with the tracklist, I believe people are more likely to browse using the gallery and thus run into the problem there)

I think a compromise might be to have to have an interaction timer, so it wont automatically change the view position if the gallery has been recently interacted with. Though that does introduce less predictable behavior.

**Comment by dwestford17** [comment]
Oh okay. Yea that does make sense. No worries. You can leave it as is.
