### ISSUE TITLE
Contextual options from tray icon are not working

### ISSUE THREAD

**Issue by msmafra** [Taiko2k/TauonMusicBox#455]
Contextual options on the tray icon: Open Tauon Music Box, Play/Pause, Next Track, Previous Track and Quit not working at start. They just work after starting a track manually.

![Captura de tela de 2021-01-25 18-52-36](https://user-images.githubusercontent.com/1005457/105770948-a2456500-5f3e-11eb-8042-0bda076f94d9.png)

https://user-images.githubusercontent.com/1005457/105770789-6f02d600-5f3e-11eb-8e94-0900fc2aa366.mp4

**Comment by Taiko2k** [comment]
What's the name of the tray extension you're using?

**Comment by msmafra** [comment]
> What's the name of the tray extension you're using?

Is "AppIndicator and KStatusNotifierItem Support"
https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by Taiko2k** [comment]
Okay I've narrowed it down. Its not the tray extension, but does seem to be related to using the Flatpak version since I can replicate the issue with Flatpak, but it works fine natively. Perhaps its related to the build of libappindicator used.

Interestingly, it seems the menu events always don't trigger when the player is stopped, but are delayed until Tauon starts playing. So it seems it's likely a Tauon related bug, but I have no idea why this happens, its one of the most bizarre bugs I've ever come across.

**Comment by Taiko2k** [comment]
Okay I found the bug, its actually related to the using GStreamer backend. Tauon blocks GStreamer backend thread processing when not in use, but this is effectively blocking the GLib main loop from processing the tray events. Ill just have to change it so it doesn't do that.

**Comment by msmafra** [comment]
I did some tests changing permissions with Flatseal, but no luck. Thanks for the feedback.

**Comment by Bauke** [comment]
@Taiko2k your fix made #441 work for me, the tray items now work when minimized initially and when no song is playing.
