### ISSUE TITLE
[Feature request] Lyrics indicator when lyrics is available

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#46]
I think it would be nice to have some indicator when lyrics is available for the playing song. 
It can also be a button so you can quickly switch to the **Lyrics View mode**. 

![alt text](https://ibin.co/4WaAJ8I7e7EY.png)

**Comment by Taiko2k** [comment]
I think it might be nicer to have it *link click* style like this.

![screenshot from 2019-02-11 11-18-48](https://user-images.githubusercontent.com/17271572/52540540-70897100-2def-11e9-88b4-154faa3fd60b.png)

**Comment by Solarunit** [comment]
I chose button, because of the Return button in the Lyrics View mode so they look the same and it will be obvious for the user. 

![alt text](https://ibin.co/4WaItmDbGeiX.png)

**Comment by Solarunit** [comment]
_link click_ style button or just a button - I think there are 2 options:

1. Button is hidden if there is no lyrics for the song.
2. Button is always visible but its only highlighted when lyrics is available. 
- active state: color text or background
- inactive state: grey color

**Comment by Taiko2k** [comment]
I'll go with the link style. 

I prefer the more minimalness of it, and I think its more in keeping with a minimal design direction that might be preferable.

I think your concept looks kinda nice, though it would difficult maintaining a good colour balance here since this is a location where the background could be any colour (Ik the lyrics view does this, but even there it needs work, but I think its less of a priority there since its not the primary view) 

As for the options, once a user sees the lyrics button/link, they'll know its absence implies there's no lyrics.

**Comment by Solarunit** [comment]
> I'll go with the link style.
> 
> I prefer the more minimalness of it, and I think its more in keeping with a minimal design direction that might be preferable.

I agree =)

**Comment by Taiko2k** [comment]
I have this implemented now
