### ISSUE TITLE
[Bug] Playlist scroll should stop when the last playlist item is on the last displayable line (of the playlist screen)

### ISSUE THREAD

**Issue by GLLM** [Taiko2k/TauonMusicBox#481]
Using the latest release (as of 10/03/2021), when the user mouse-scrolls in a playlist, he sees
![image](https://user-images.githubusercontent.com/3989573/110691022-e5a11d80-81e4-11eb-9b1e-7f9eaf95fc4e.png)

and if the scrolling goes on, you can even get to this :
![image](https://user-images.githubusercontent.com/3989573/110691118-05384600-81e5-11eb-99a8-5141e86440d2.png)

The scrolling should stop at this stage (when no more info shall be displayed) :
![image](https://user-images.githubusercontent.com/3989573/110691223-2e58d680-81e5-11eb-9d17-8ef76e808a83.png)

What's your opinion @Taiko2k ?
Thanks
GLLM

**Comment by Taiko2k** [comment]
Its not a bug really, more of a quirk that's stuck around due to having developed a workflow around it. It offers two main advantages:
  1. When you click an album, it will always align to the top of the tracklist area. So the first track will always be the first shown.
  2. You can scroll then drag and drop to have an album perfectly aligned. This order feels more natural to me than drag and drop then scroll.
 
The downside is the user can get a little lost and assume the playlist is empty when its not. At this point I don't feel that trade is worth it.
