### ISSUE TITLE
Gallery View issue

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#51]
I think that single click should select and double click to play album. 
And maybe add "play album" in the context menu.

**Comment by Taiko2k** [comment]
This is intentional more or less. I've had other users bring this up too.

I think I prefer how this works personally, though I realise its a little unexpected, I'd be interested to hear from any users who've used it this way for a while as to what their feedback is.

**Comment by Taiko2k** [comment]
Actually, I could possibly add this as an option, something like "Single/Double click to play albums in gallery"

**Comment by Solarunit** [comment]
Maybe. BTW I also like that you can switch to the Gallery View using Tab and select albums using arrow keys.
And then switch back to the Art View and use arrow keys for playlist and tabs navigation!

**Comment by Solarunit** [comment]
I'm curious why did you decide to implement scroll-bars on the left?

**Comment by Taiko2k** [comment]
Because I'm left-handed and want to rebel against the right-handed (joke). 

Though really, there's no exact reason, though partly, its to keep the center of the window clean and have scroll bars on the sides so they are out of the way. 

Also if the playlist scroll bar was on the right, it would mean both the side panel drag area and scroll area hit boxes would need to be narrow so they don't collide, and part of the design direction is to have big hit boxes, therefore, I think its better to have these apart.

**Comment by StrangeSeasOfThought** [comment]
Issue: The gallery won't jump to the new album after track change via shuffle.

**Comment by Taiko2k** [comment]
It actually doesn't change when the track *automatically* changes regardless of shuffle. I think this was intentional of me, because, if you were actively browsing the gallery, you wouldn't want it jumping around on its own.

**Comment by StrangeSeasOfThought** [comment]
> It actually doesn't change when the track _automatically_ changes regardless of shuffle.

I don't think this is correct. Only seems to be the case when shuffle is enabled. v0v

**Comment by Taiko2k** [comment]
Okay, I've added a config option called `show-current-on-transition` to the config file. Let me know if you find that works well for you.

**Comment by StrangeSeasOfThought** [comment]
Works well, thanks!
