### ISSUE TITLE
Tauon scrobbles all plays twice

### ISSUE THREAD

**Issue by gigawhitlocks** [Taiko2k/TauonMusicBox#566]
This may only happen when using an Airsonic-compatible server, I don't know. It also may only occur with the Airsonic-compatible server that I use, Navidrome.

But basically what the title says: everything gets scrobbled twice to Last.FM.

I won't open any more issues against Tauon unless you request. Too many bugs to report them all; going to go back to using Clementine unless you're interested in reports for the rest of the bugs I have encountered, but regardless I can't use a media player that is going to mess up my scrobbles any more than Tauon already has.

**Comment by Taiko2k** [comment]
Is it the case that you enabled lastfm on both Tauon and Navidrome? This situation would cause double scrobbles.

**Comment by gigawhitlocks** [comment]
Navidrome's scrobble feature is for the web UI only.

I do have scrobbles enabled in the Navidrome UI but other clients (DSub, Clementine) do not cause double scrobbles even though I also have those clients configured to scrobble directly.

**Comment by deluan** [comment]
Hey, Navidrome developer here. Let me clarify it: If you enable Last.fm scrobbling in Navidrome's Personal settings, it will by default enable scrobbling for **all** players that call the `/scrobble` endpoint, not only the web UI. You are probably not getting it from DSub because you need to [enable it in DSub to send the scrobble to the server](https://github.com/navidrome/navidrome/issues/593#issuecomment-715646271)

So, if you have it enabled in the Personal settings, and if Tauon calls the `/scrobble?submission=true` AND sends the scrobble directly to Last.fm, you'll see double scrobbles. You have two options: Disable Tauon sending scrobbles directly to Last.fm (if that's an option), or disable the Last.fm scrobbling only for Tauon in Navidrome's Players view. 

I hope this is not confusing to follow. I'll write a page to better explain how scrobble works with Navidrome and Subsonic clients, because the Subsonic API calling it "scrobble" makes it very confusing.

**Comment by gigawhitlocks** [comment]
>You are probably not getting it from DSub because you need to enable it in DSub to send the scrobble to the server

ohhhhhh.. shoot, I am so sorry @Taiko2k for the bad bug report; thank you for the clarity @deluan ; closing this
