### ISSUE TITLE
3.7.0 Breaks Last.fm

### ISSUE THREAD

**Issue by SehWho** [Taiko2k/TauonMusicBox#57]
In 3.7.0, scrobbles no longer work.  I tried to log in again to see if that would fix the problem, but no matter what pressing the log in button does not open the page in my browser and Tauon crashes at the moment it's pressed.

I've just gone back and confirmed that this doesn't happen on 3.6.0.  [Here's what the terminal displays on the login crash](https://pastebin.com/MQh0TxYL), though I don't know if that's helpful.

This is on the flatpak version.

**Comment by Taiko2k** [comment]
I see, this is actually a packaging issue, I must have accidentally deleted the network permission for the flatpak sandbox, therefore its not getting network access. 

(Though I should probably improve the error handling on that rather than simply crashing)

I've updated the `flatpak.tauon` on the release page. See if installing it now fixes it.

**Comment by SehWho** [comment]
Last.fm is having issues and not displaying scrobbles at the moment so I can't tell for sure that it's working, but the login now works properly so I imagine it is.  Thank you :)
