### ISSUE TITLE
[Jellyfin] Albums by name, not by artist

### ISSUE THREAD

**Issue by Tau5** [Taiko2k/TauonMusicBox#582]
If a song in an album has a different artist, it is separated from the rest of the songs in a separate album

**Comment by Taiko2k** [comment]
When you view the track info for those tracks, do they show as having the same "album" field?

**Comment by Taiko2k** [comment]
OK I assume this is a Jellyfin specific issue.

I do see that theres some issues there. I've now committed a change with new enhanced *keep albums together* technology. So, this should be fixed in the next release.

Seems to still not quite work 100% of the time but that's more or less down to being Jellyfins fault now.

**Comment by Taiko2k** [comment]
> It seems that when I click the option to edit the generator it auto-updates and applies the changes, but when re-importing again it still generates it unordered

Ahh. I've now pushed another commit that should fix it. Let me know if its working now.

**Comment by Taiko2k** [comment]
New release is out now, let me know if any issues persist.
