### ISSUE TITLE
Playing track highlighting

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#60]
Some themes have almost invisible highlighting of the playing track

Cucumber Splash

![alt text](https://ibin.co/4XxAT54nrkBa.png)

Sky

![alt text](https://ibin.co/4XxAuYXQSncM.png)

**Comment by Taiko2k** [comment]
For the Sky theme there isn't a highlight on the playing track at all which was intentional as part of the design of the theme.

As for the others, I never had a problem identifying which was playing, though perhaps this could be harder to tell on different displays. I could be brighten them a bit, like this:

![screenshot from 2019-02-23 14-36-45](https://user-images.githubusercontent.com/17271572/53279856-dde6bb80-3778-11e9-88c3-10609f4a7087.png)

**Comment by Solarunit** [comment]
Maybe it's my monitor settings (low brightness). Selected track is ok I think, but playing track is hard to identify quickly.

**Comment by Solarunit** [comment]
> For the Sky theme there isn't a highlight on the playing track at all which was intentional as part of the design of the theme.

Sky theme is my favorite. Cucumber Splash is very nice too.

**Comment by Taiko2k** [comment]
Thanks. Rose and Astro are my personal favorite. 

Sky is actually the oldest theme of them all (There were older ones, but I removed them).

Wasp is probably the next candidate to be removed, I'm not sure people use it much.

**Comment by Solarunit** [comment]
I like Wasp =)
Not a fan of Mindaro, Astro, Lime and Vape.
