### ISSUE TITLE
Tauon permanently shows as playing sound even when music is stopped

### ISSUE THREAD

**Issue by C0rn3j** [Taiko2k/TauonMusicBox#61]
Tauon 3.7.0 on Arch Linux running KDE.

![image](https://user-images.githubusercontent.com/1641362/53492203-96be3a80-3a98-11e9-985c-62c09718c73e.png)

Tauon is permanently showing as playing audio even when paused, which makes it annoying to track down which window is playing some music I want to stop.

**Comment by Taiko2k** [comment]
I see what you mean, I am able to fix this.

KDE detects this by the open audio connection, most other apps (notably GStreamer based) seem to close the connection when paused, though personally I found that to be annoying since I once had an amplifier that made a loud clicking noise whenever initialized which drove me mad.

So I might just add this as KDE specific hack, or maybe a setting that defaults to on when KDE is detected.
