### ISSUE TITLE
Support for High Resolution Files

### ISSUE THREAD

**Issue by wielandwagner** [Taiko2k/TauonMusicBox#651]
VLC and DeadBeef have found a way to support pass-through of hi-res (24-96 to 24-192) to an external DAC. Would you add this functionality to your AUDIO set-up. And thank you for a superbly conceived music player.

**Comment by Taiko2k** [comment]
Currently (Speaking in regards to Tauon's 'Phazor' backend), the bit depth is passed onto the audio server as is, and the samplerate is resampled to 48khz (Using a moderately high quality converter). I picked this rate because that's what Pipewire defaults to anyway. (I believe Pipewire will choose the highest bit depth available when connecting to your DAC, so bit depth at least is not any problem).

There exists a trade-off between development cost and real world benefit, I chose to draw that line where I think it makes most sense. Basically doing things like bit-perfect output is way more trouble than its worth IMO. 

From what I know, some people can hear the difference between 16 and 24bit so that's important, but sample-rates above 44.1khz *shouldn't* be discernable. Resampling artefacts are real, but they're *very* small, I don't believe they're noticeable, from my understanding.

Sure it would be nice to just have that option but adding and maintaining options has real world cost.
