### ISSUE TITLE
Radio Paradise (AAC stream) plays for a instant, then stops

### ISSUE THREAD

**Issue by axelsimon** [Taiko2k/TauonMusicBox#664]
Hi, and thanks for TauonMusicBox, it has become my daily music player and i really enjoy it!

One small problem is when trying to play Radio Paradise's AAC stream from my list of saved radio stations, it often plays for about 0.5 seconds, then stops outputting sound, but the name of the currently playing song and artist still appear. I can click on play again mulitple times, with the same effect: play for 0.5 seconds or so, stop outputting sound. Sometimes, after about 5-10 tries, it "sticks" and keeps playing, other times i just can't get it to keep playing and i have to listen to something else.

This happens on this URL: https://stream.radioparadise.com/aac-320
It does _not_ happen on this URL: https://stream.radioparadise.com/flac

I would use the FLAC stream by default, but it doesn't send artist and song metadata, which ruins LastFM stats (it also takes much longer to start playing, but that's just due to the size of FLAC and therefore the time it takes to fill the cache)

**Comment by Taiko2k** [comment]
I've found a bug that's causing this and committed a fix now. (Bad programming habits coming to bite me)

**Comment by axelsimon** [comment]
Wow, that might be the quickest reaction and time to fix i've ever seen! haha :)

Fore anyone interested (like me), this is the commit: https://github.com/Taiko2k/TauonMusicBox/commit/71276b1022142d40cff89003e209c44517231ebb

Thanks! Closing this issue then.

**Comment by Taiko2k** [comment]
Since you're interested ill explain it in more detail:

Background; In abstract: The stream data is downloaded to a buffer. This buffer has a limited size which raises the question of what to do if the buffer ever reaches full intended capacity. The proper way of handling this would probably be to limit the download rate until more of the buffer has been consumed. 
 
However my more dirty design just has it bail out and stop if this situation happens. With the solution just being to increase the size of the buffer to the point where this is unlikely. 

The bug is that the buffer size was set too low. Meaning the stream would likely immediately stop with a large initial burst of data. This size value was set as a "magic number" in two separate locations. I had set one to the intended value but forgot to update the other. 

In this case, the bug only affected Shoutcast streams. And in this case the larger 320kbs stream would likely trigger the bug, but testing was only ever done with lower bitrate streams.

Important programming lessons:
 - "Magic numbers" are bad, always avoid using them.
 - Avoid duplicating code. Better to have a single function than mirroring co-dependent code in multiple locations.
