### ISSUE TITLE
phazor: pipewire sink

### ISSUE THREAD

**Issue by jansol** [Taiko2k/TauonMusicBox#717]
Pipewire seems to be the undisputed future of linux audio and while there is no acute need yet (pipewire-pulse works like a charm), mpv and mpd already have native sinks for it so tauon should probably also eventually get one. Apparently at least the one in mpv was a breeze to code, too.

I'm somewhat interested in writing this myself but most likely won't have time to even think about it in detail before summer so if someone else is interested in implementing this, by all means consider it up for grabs. I'm mostly posting this as a reminder for myself and as a tracking issue for the feature.

**Comment by Taiko2k** [comment]
Yeah, there's no immediate need, but native pipewire could be a nice to have. Let me know if you want me to give any pointers on where to start in the phazor source code.

If enough distros ship pipewire we could consider just dropping pulseaudio.

**Comment by Taiko2k** [comment]
Thing is though I used the pulseaudio "simple" API, but pipewire has no equivalent (last time I checked) so it would be a bit of work, it's not just a drop in replacement.

**Comment by jansol** [comment]
I guess the move to miniaudio makes this obsolete, would make more sense to add pipewire support to miniaudio instead.

**Comment by PranavBhattarai** [comment]
> If enough distros ship pipewire we could consider just dropping PulseAudio.

Some progress on defaults:
Ubuntu ---->> pipewire  (22.10)
Debain ------>>> pipewire   (soon, experimental for now)
Fedora ------->>>> pipewire (f34)
...... 
many other distros like EndeavourOS, System76, OpenMandrive, etc

**Comment by Taiko2k** [comment]
interesting. But as mentioned, this is now dependent on the upsteam project miniaudio. As pipewire-pulse seems to work just fine there's not any immediate benefit to adding native pipewire.

**Comment by PranavBhattarai** [comment]
@Taiko2k The reason I had to make the comment is that TauonMusicBox didn't couldn't play the majority of songs.
Out of 15 songs, it could only play 3 of them.
I didn't know about this app until yesterday, wanted to try it. Added the music library and tried to play some songs, but it couldn't.

Distro: Fedora 36
App installation mechanism: Flatpak

I have all non-free & free codecs related to both audio and video. I wonder what went wrong. So, I just uninstalled it.
My _wild_ guess is:
- Either Tauon didn't use the codec installed in the system _(because of Flatpak & its sandboxing!)_
- Or, Tauon lack of Pipewire (but it doesn't make sense since 3 songs are playing)

**Comment by Taiko2k** [comment]
Yeah it wouldn't be a Pipewire issue I wouldn't think. Could be a codec issue.

Try run `flatpak install org.freedesktop.Platform.ffmpeg-full//21.08`, though, that should have installed automatically. Otherwise can tell what codecs you have that are and aren't working, or it there seems to be any other pattern?

**Comment by PranavBhattarai** [comment]
FFmpeg is already installed as you can see in the part of the log below:
```
Which do you want to use (0 to abort)? [0-6]: 6
Skipping: org.freedesktop.Platform.ffmpeg-full/x86_64/21.08 is already installed
```
Except for 21, 63 & 7 whose first initials are blue in color, only those songs are playable; as you can see below:
![image](https://user-images.githubusercontent.com/32763112/185077441-42b879b2-ca6b-47e5-966a-a3a79031289b.png)

> Otherwise can tell what codecs you have

All of them, a lot of them as you can see below:
![image](https://user-images.githubusercontent.com/32763112/185079701-97630cb4-44a9-4951-b8ca-0b00ae33ea98.png)

**Comment by Taiko2k** [comment]
Hmm its not a codec issue, since its since those tracks don't have metadata scanned, and Tauons metadata scanning is independent of codec support.

Try run Tauon from terminal `flatpak run com.github.taiko2k.tauonmb`. Could you tell me what error, if any, it prints when you attempt to play a track that doesn't work?

**Comment by PranavBhattarai** [comment]
@Taiko2k 
```
 ⟹  flatpak run com.github.taiko2k.tauonmb
Tauon Music Box v7.3.2
Copyright 2015-2022 Taiko2k captain.gxj@gmail.com

Window size: [1120, 600]
Detected running as Flatpak
Installed as Flatpak
User files location: /home/pranav/.var/app/com.github.taiko2k.tauonmb/data/TauonMusicBox
Found XDG-Downloads: /home/pranav/Downloads
Found XDG-Music: /home/pranav/Music
Install directory: /app/bin
Using crash workaround for gdk crash
Database loaded in 0.001 seconds.
Copy tray icons to data directory...
Start controller server
Start PHAzOR backend...
Using SDL version: 2.0.16
Applying theme: Neon Love
pa: ERROR, encoding format not supported!
ph: Load file failed
pa: ERROR, encoding format not supported!
ph: Load file failed
Start PHAzOR backend...
pa: ERROR, encoding format not supported!
ph: Load file failed
ph: Using samplerate 48000hz --------------------------->> I selected the song which the player can play
pa: ERROR, encoding format not supported!
ph: Load file failed
^Zfish: Job 1, 'flatpak run com.github.taiko2k.…' has stopped
```

**Comment by Taiko2k** [comment]
Interesting, those must be rare mp3s. At this point I would need to have one of those files on hand for testing in order to fix compatibility, if you're willing to upload/send me one.

**Comment by PranavBhattarai** [comment]
@Taiko2k Ok, I have compressed an audio/song named "Rhythm of Shiva", and have attached it here.

![image](https://user-images.githubusercontent.com/32763112/185289698-ead17d81-ad7a-4808-a7f0-009861b84884.png)

[Rhythm of Shiva - Armonian.zip](https://github.com/Taiko2k/TauonMusicBox/files/9367484/Rhythm.of.Shiva.-.Armonian.zip)

_As a side note, I use "Telegram bots" to download audio/songs in 320Kbps. There are also some bots to download Flac audio (which I don't prefer because of its massive size._

**Comment by Taiko2k** [comment]
Right okay found and committed a fix for the issue.

The issue is those aren't actually MP3's, they're DASH MP4's. Tauon didn't recognise its file signature and couldn't fall back to file extension to guess an appropriate codec to use. By now adding signature detection for DASH, these will now play even with incorrect file extension.

**Comment by PranavBhattarai** [comment]
Isn't it weird a song downloaded in "DASH MP4" codec _(something that I have never heard of)_, but just **renamed** into .mp3? 

WT... 😅😅

**Comment by jansol** [comment]
Closing this for now since it's obsolete and to get it out of my open issues list.
