### ISSUE TITLE
Import music from external devices

### ISSUE THREAD

**Issue by GreyDireWolf** [Taiko2k/TauonMusicBox#80]
Will Tauon support importing music from external devices such as android device or USB?

**Comment by Taiko2k** [comment]
It's not something that I had planned.

A shortcut for importing the home music folder works well, since we know exactly where it is and what its for, but devices... that gets messy I think.

Android MTP is another whole can of worms, I kind of don't want to go there. 

Apart from that, I don't see that it hugely satisfies a use case more than opening your file manager and dragging a folder from a USB drive, its fairly quick to do. Maybe better to keep things minimal than clutter the menus as well.

**Comment by legacychimera247** [comment]
so if i have music on an external hard disk, dragging n dropping the folder in the playlist like any other local folder panel would not work?

**Comment by Taiko2k** [comment]
@legacychimera247 No, dragging a folder from another filesystem does work, as I'm suggesting. Or at least, it would work for an internal HDD or external USB drive etc...

But would not work for Android since that uses its own protocol. When you access an Android phone from your file manager, its not really mounting the filesystem but interacting directly with the protocol itself, so dragging a folder would not work in that case.

The way I see this feature request is like having a menu option `Import from USB Drive A` in addition in the the existing `Import ~/Music` function.

**Comment by legacychimera247** [comment]
ok, this answer my question then, well honestly i agree with you perfectly...

**Comment by Taiko2k** [comment]
Indeed I meant MTP. It just seems like a headache to implement and deal with.

I could use a library to access it like python-mtp. Though right there in the readme it says:

> Little warning: MTP is a crap and doesn't work well 

I'm like, yeah exactly!

**Comment by gibranlp** [comment]
i am trying to add music from a separate internal drive, with no success, i even added the path on the config file but no music is added, is there a way to do it?

**Comment by Taiko2k** [comment]
Did you try dragging and dropping from file browser? (Btw, you can't import music using the config file).

**Comment by gibranlp** [comment]
I added the directory as a Download folder, so Tauron will keep watch, and tried also dragging and dropping but just nothing happens.

**Comment by Taiko2k** [comment]
Something *should* happen when you drag and drop. Hmm... What file manager are you using?

Also, could you tell me, are you using the Flatpak or AUR package? (If you're using Flatpak, did you grant the permission?)

An alternate way of importing is using "Open With" from a file manager, maybe see if that works.

**Comment by gibranlp** [comment]
Music is all mp3, aac, mp4.

I'm using ElementaryOS.

Trying to open a file with the context menu does the work (open with Tauron), but then i would have to open each single file, or at least each folder which i have like 1000 of them.

Drag and drop from my music folder does not work either, i think is the elementary file manager.

Im using the Flatpak version.

is there any other way to import?

There i solved it all i had to do is this

ln -s /direction of my/other drive/ ~/Music

Now it works its importing all the music files now, awesome thanks =)

**Comment by smaragdus** [comment]
Sun Jun 23 17:41:30 GMT+03:00 2019 Taiko2k/TauonMusicBox <reply@reply.github.com>: Music is all mp3, aac, mp4. I'm using ElementaryOS. Trying to open a file with the context menu does the work (open with Tauron), but then i would have to open each single file, or at least each folder which i have like 1000 of them. Drag and drop from my music folder does not work either, i think is the elementary file manager. Im using the Flatpak version. is there any other way to import? There i solved it all i had to do is this ln -s /direction of my/other drive/ ~/Music Now it works its importing all the music files now, awesome thanks =) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by svastian99** [comment]
The app works well with music files on Linux partitions ... but  does not allow me to add music to the library from NTFS partitions.

**Comment by Taiko2k** [comment]
@svastian99 This should work. If you're using the Flatpak version, did you grant the permission?

**Comment by svastian99** [comment]
thanks it worked! {I didn't know what I should do that}

**Comment by Taiko2k** [comment]
@svastian99 There's supposed to be an error message displayed when you try drag and drop and it failes, but maybe there is a bug where it disappears too quickly.

![Screenshot from 2019-08-04 20-53-26](https://user-images.githubusercontent.com/17271572/62421703-fb418d80-b6f9-11e9-8d18-18e2ee71a401.png)

**Comment by lastweakness** [comment]
Shouldn't this be closed?

**Comment by Taiko2k** [comment]
@lastweakness Yeah but now its awkward cause OP will get an email notification that I closed it and be like WTH :disappointed_relieved:. Ok ill do it quickly and get it over with.

**Comment by C0rn3j** [comment]
Best open a new issue since this is closed 5 years ago.
