### ISSUE TITLE
Scroll bar improvements

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#82]
I like the player minimal style. :heart: 
But when you have a very long playlist and you try scrolling with mouse wheel or using up/down keys, I feel that something is missing (Scroll bar). So the idea is to show Scroll bar only when you scroll. Maybe with some fading effect.

**Comment by Taiko2k** [comment]
Could you elaborate?

**Comment by Solarunit** [comment]
edited 1 post

**Comment by Taiko2k** [comment]
I have a change for this in the latest version now. I think fading might be more distracting so I went with just a short delay to switching off.

**Comment by Solarunit** [comment]
Oh, thanks! Scrolling is more practical now. 

> I think fading might be more distracting so I went with just a short delay to switching off.

Maybe a very short fading when scroll bar is disappearing? :bulb: 

----
Because scroll bar overlaps two areas (playlist panel and playlist), I see a small distraction here - especially noticeable on Astro theme:

![alt text](https://ibin.co/4dE4jmvwSkkB.gif)

I've noticed that scroll bar is different on the light theme and it overlaps the track numbers:

![alt text](https://ibin.co/4dE6gvePjfvk.png)

**Comment by Taiko2k** [comment]
Yeah that is a bit of an issue, I'm not too concerned about the Astro one, but the light theme one is kinda bad. I'm not sure fading would help in either case.

Its a bit difficult... I don't want to move the track number over because it looks neat when without the scroll bar, but I also don't want to make the scroll bar smaller.
