### ISSUE TITLE
[Feature request] Adjustable buffer time

### ISSUE THREAD

**Issue by daltroaugusto** [Taiko2k/TauonMusicBox#846]
I saw the changelog for older versions, and I noticed that it was an option, in version 7.2<. But for some reason it was removed. For my use-case (which maybe is a "limit use-case"?) the default buffer don't seems to be enough for gapless playback. Here it is: I'm running a local Navidrome (Subsonic API) server with song files stored in a Google One drive, that is mounted via rclone. Usually, in other players which have this option, like Strawberry, foobar (WINE) or MusicBee (Windows), I'm able to set buffer size manually to 10s (10,000ms) and it's enough to get gapless playback. My internet connection is speedy enough (300Mbit/s) for it, even with lossless files. I think the thing here is probably some rclone mechanism to get the file.

Well, anyway, I'd really appreciate to have this option/feature in Tauon as well. I think it's simply the best Linux-native player we have right now, it have amazing interface, great and exclusive features (for eg. with Strawberry you can't rate Subsonic songs, and their lyrics component is worse than Tauon's; foobar interface is way more rustic and it's not native etc).

Ps.: I'm using rclone with some tweaks and appropriate settings like vfs-cache mode full, a script that automatically scans (and cache) dir structure etc.

**Comment by Taiko2k** [comment]
Yes there was previously a buffer setting that was removed. I may or may not re-implement that but in any case it wouldn't help here with gapless playback. It issue being that *when* Tauon preloads the next file is still fixed. 

I assume you're not using the Subsonic API with Tauon but the mounted filesystem as if they were local files. I do have a setting that may help in this case, under Settings > Audio > Cache local files

![Screenshot from 2022-09-29 20-06-16](https://user-images.githubusercontent.com/17271572/192963218-b9e87ce7-206a-4eae-abfb-17e27691f639.png)

With this setting enabled Tauon will try to immediately preload the next track at the start instead of the end of the current track.

Let me know it that works well for you.

**Comment by daltroaugusto** [comment]
> Yes there was previously a buffer setting that was removed. I may or may not re-implement that but in any case it wouldn't help here with gapless playback. The issue being that _when_ Tauon preloads the next file is still fixed.
> 
> I assume you're not using the Subsonic API with Tauon but the mounted filesystem as if they were local files. I do have a setting that may help in this case, under Settings > Audio > Cache local files
> 
> ![Screenshot from 2022-09-29 20-06-16](https://user-images.githubusercontent.com/17271572/192963218-b9e87ce7-206a-4eae-abfb-17e27691f639.png)
> 
> With this setting enabled Tauon will try to immediately preload the next track at the start instead of the end of the current track.
> 
> Let me know it that works well for you.
> 
> Edit: In the case of Subsonic, this behavior is always enabled regardless of the above setting

Those ones were already enabled. Well, anyway, I've tested it again and it was problem just some temporary issue. I'm using Subsonic localhost instance actually, cause this way Tauon doesn't needs to rescan the entire library (and consume GDrive API and bandwith etc heh).

Thanks! I'm closing the issue.
