### ISSUE TITLE
Issue with full screen mode

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#88]
the title pretty much explains everything, yeah i know  i can resize the window but i would prefer a full screen option

**Comment by Solarunit** [comment]
F11?

**Comment by legacychimera247** [comment]
well a button near the usual close / minimize button would be better but if f11 does the job, then it's good, should try that...

**Comment by legacychimera247** [comment]
tried that and while is really useful is not what i meant, i meant a maximize windows, that would be useful...

**Comment by Taiko2k** [comment]
It would be possible to have a maximize button, though, the main reason I did not was because in most desktop environments its already easy to maximize windows by dragging them to the top of the screen. I think this is a much more natural feeling workflow than clicking a button. Does the desktop environment you use not have this feature?

**Comment by legacychimera247** [comment]
i'm using mate and yes it have it, but simply i have not thought about it :P anyway seems that after using f11 i cannot go back so i think there is a bug here...

**Comment by Taiko2k** [comment]
So, after pressing F11 to enter full screen, pressing F11 again won't exit it? This happens every time?

**Comment by legacychimera247** [comment]
exactly...i can only go into mini mode...

**Comment by Taiko2k** [comment]
Strange, I can't seem to replicate this. I even tried with the MATE desktop and it was working as expected.

**Comment by legacychimera247** [comment]
i will try when i'll get back home :), anyway i noticed that in mini mode i have the actual mini mode but around that the screen stays black like if it is still in fullscreen...

**Comment by legacychimera247** [comment]
so, swapping theme with f2 works as expected, it's just the f11 witch is not working anymore...

**Comment by Solarunit** [comment]
F11 works on budgie. 
But there is a problem when using workspaces:
1. tauon in fullscreen on the workspace_2
2. switching to the workspace_1 using hotkey
3. switching to the workspace_2 - tauon is minimazed. I can bring it back by clicking on the panel or by using alt+tab.

BTW Kodi in fullscreen works fine.

**Comment by Taiko2k** [comment]
@Solarunit I can replicate this switching workspace issue too.

Exiting full-screen is working fine for me though.

In either case, these seems to be a bug/behavior of SDL2. I'm pretty sure the code is correct on my side so not much I can do unfortunately. (Although being able to enter mini-mode from full-screen is unintended, ill fix that)

**Comment by legacychimera247** [comment]
so i do assume there's no way i can switch back?

**Comment by Taiko2k** [comment]
Closing the app and opening it again should for sure exit fullscreen. It wont return to fullscreen, but it will return to maximized if it was mazimized.

You should be able to exit maximized by dragging the top panel, then even if the window is big, at least you should be able to move and resize the window (drag the bottom right corner preferably, or right on any of the edges of the window)

**Comment by legacychimera247** [comment]
well seems i'm not able to do anything of the things you mentioned...

**Comment by Taiko2k** [comment]
So... there's three states the window can be in, full-screen (fake fullscreen / borderless window actually), maximized, and standard window.

I assume it must be in maximized because I'm almost certain it wont re-enter full-screen automatically. If its in maximized, you should be able to drag it down using the top panel. Unless the DE is not letting it somehow (or unless there is a bug in Tauon not marking the top bar as drag-able for some reason), unfortunately I haven't programmed a keyboard shortcut to unmaximize. Perhaps I will add that in.

In the mean time, as a last resort, exiting then deleting `state.p` from the program data folder (this will reset everything except playcounts) should reset it to windowed mode.

**Comment by legacychimera247** [comment]
done, and here's what happens...

![Schermata a 2019-04-15 14-57-36](https://user-images.githubusercontent.com/22254556/56134585-2fe4da00-5f8f-11e9-964f-185cef66cc05.png)

i ended up deleting the state file and everything returned as normal, but

program was not full screen, and dragging the app on the top screen doesn't do anything (altough mate has this function), so i right clicked on the icon on the top bar and selected maximize. the app maximized and now even the drag n drop to maximize it's working. I really dunno...
