### ISSUE TITLE
have an artist view 

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#89]
it would be nice to have an artist view  in tauon. As of now the left panel is used for playlists but would be nice if it could be usable for an artist view too, and then the middle panel would be used for displaying albums and releases for the selected artist

of course this should be configurable cause not everyone could want to organize  organize things this way (in case the thing is doable of course :) )

**Comment by Taiko2k** [comment]
Here's a concept of what I'm thinking here. Similar style to how Music Bee and Lollypop do it.

![Screenshot from 2019-04-21 18-46-35](https://user-images.githubusercontent.com/17271572/56466407-f831d280-6465-11e9-9d75-1428b63201ce.png)

**Comment by legacychimera247** [comment]
honestly, go for it. It absolutely rocks and exactly what i was looking for...

would be even nice to have artists organized by surname as you would do in a record store

for example bruce springsteen would be at S letter or Kilye Minogue at M, or bands without suffix, for example The Goo Goo Dolls would be at G and The 1975 would be at numbers...

**Comment by Taiko2k** [comment]
That would be doable, but... I kind of think that deviating from pure alphabetical order is the point at which confusion arises. Take for example `Carly Rae Jepsen`, I suppose that should go under J, but what about `Matthew Good Band` should that go under B? What about `Red Hot Chili Peppers`.

But if we know its pure alphabetical, we don't even have to think, you would instantly know those are under C, M and R respectively.

**Comment by Taiko2k** [comment]
I was thinking of having fancy filtering, but perhaps simply locating the first appearance of an artist in the current playlist (and playing on double click) is a more streamlined approach.

The downside is if the user has the artists fragmented in the playlist and not grouped together, but I think that's somewhat uncommon.

Btw heres the latest screenshot, I decided against rounded thumbnails:

![Screenshot from 2019-04-23 20-49-49](https://user-images.githubusercontent.com/17271572/56572126-8945ac80-6612-11e9-9fcf-826483d18679.png)

**Comment by legacychimera247** [comment]
well of course bands would go on the first letter they have, got used to this sorting by using lollypop for sometimes and i think it's pretty logical, but ok this is a point of view, as for the "i" "the" and others, well i must admit that it just felt right

the avatars are good even squared and anyway less space is wasted, and honestly i do guess artists should just be sorted alphabetically so it's easier to find them and albums inside grouped by year with the usuals sorting options already present.

as for carbon based lifeforms you gave me something new to explore xD

**Comment by Solarunit** [comment]
The last screenshot looks better. How user will switch to the artist view? Will the playlist panel still be available? 

How is an artist list is generated? From the all created playlists?

@Taiko2k do you plan to add a music library?

**Comment by Taiko2k** [comment]
@Solarunit I have it as a **right click** of the side panel top corner button to toggle between playlist and artist list. Its currently generated from the viewed playlist only (though maybe I could add a global mode). Then I have it pass through a threshold to filter out noise such as artists from compilation albums. 

As for a music library. I don't have any plans for anything major at the moment. I'd prefer to try make small adjustments to the current system to try better fulfill what people want to be able to do. Certainly not like AIMP2 where it had a whole separate library UI.

**Comment by legacychimera247** [comment]
i personally think the artist list is wonderful, as for the rest, the player already works fine so no need to rewrite any music library, the main idea behind the player is already right because it let us organize music using a very small amount of memory without being just a list player like for example deadbeef or exaile (no offence to others here)

**Comment by Taiko2k** [comment]
This is now live, hopefully my implementation works well.

**Comment by legacychimera247** [comment]
as much as this is lovely, i cannot find how to enable the artist view...i am missing something?

**Comment by legacychimera247** [comment]
ok, found it, trying it :)

**Comment by Taiko2k** [comment]
I wrote a couple of notes about it in the release info https://github.com/Taiko2k/TauonMusicBox/releases/tag/v4.2.0

**Comment by StrangeSeasOfThought** [comment]
I'd love to have an option in the settings to always use/display album artist (or AlbumArtistOrArtist in case album artist tag is empty) instead of artist.

**Comment by Taiko2k** [comment]
@StrangeSeasOfThought So, if I understand the core issue, its that you have many comp/mixtape albums, and the artist list is not showing the album-artist of those, but you want it to?

**Comment by StrangeSeasOfThought** [comment]
@Taiko2k Well... I don't listen to comp/mixtape albums at all. But I listen to e.g. Korean (indie) music, so I use the artist tag for the artist name in Hangul (which is also the one I want to be scrobbled), the album artist tag for the international/English/romanized spelling of the name (which I prefer to be displayed, whenever I have visitors because they can't read Hangul; plus because of some other reasons, too).

> If that is the case, maybe it would make sense to always list both album artists and artist (where those are different).

This wouldn't be an ideal solution in my case because most of them are different (Hangul vs. not Hangul), so it would basically list them twice.

For example, Cantata uses the album artist tag by default (or artist tag if a song has no album artist), to group songs and albums. That'd be fine.

**Comment by Taiko2k** [comment]
That makes sense to me then. So you would want that easy to switch. I've added this setting. With it enabled, it will always prefer using the album-artist field if present. I presume this should work as you expect.
![Screenshot from 2019-05-23 11-17-15](https://user-images.githubusercontent.com/17271572/58215377-b9858580-7d4d-11e9-82d3-984370cce94b.png)

**Comment by StrangeSeasOfThought** [comment]
Cheers! I'll take a look at it later.

By the way, when I use artist view list + gallery mode: The gallery jumps to whichever is the last album in the gallery when selecting an artist. Wouldn't it be better to immediately jump to/show the albums released by the selected artist instead?

**Comment by Taiko2k** [comment]
Oh, its intended to, that is a bug

**Comment by StrangeSeasOfThought** [comment]
I love the album artist view. Thank you!

Some issues:

I) It doesn't remember the setting between sessions, so I've to reenable it every time.
II) The list is being ordered like this: #-A-Z-a-z rather than #-aA-zZ. Is this intended?

This might be on my end, not sure, yet:
III) I only use local artist artwork. All artwork is in the same folder (200x200; .png). Tauon can't find 5 of them and displays blank/no images instead (I also tried .jpg and .jpeg). If I replace 'faulty' image ArtistA.png by renaming a working one (from ArtistB.png to ArtistA.png), it's being displayed properly for ArtistA now. So the fault seems to be with those 5 images somehow. However, other music players display all of them without any issues.
Because only 5 of my artist images are not being displayed, I can replace them easily with new ones. Other users who prefer local artist artwork, might have more missing, though. So maybe you might want to take another look at the code. v0v

**Comment by Taiko2k** [comment]
@StrangeSeasOfThought 
I) I forgot about that.
II) Not intentional, just simply something I had not noticed.

Ive committed a fix for both of these now.
