### ISSUE TITLE
[Flatpak] transcoder is not working

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#91]
well i set the transcoder to code in ogg at 192 kbs and i tried transcoding an mp3 album to ogg, the process was started but then it just done nothing. The data folder contained the actual folder for the transcode but it was completely empty even after waiting several minutes

by the way, why only ogg opus and flac?mp3 would be nice too since mediaplayers and car stereos generally only read mp3 and at least m4a...

**Comment by Taiko2k** [comment]
I can conform I can replicate this. Another Flatpak issue, it seems that ffmpeg included in the runtime is borked. I think I have a working solution though. Ill push that update in a day or so maybe.

Also, I'll enable MP3 support. (I had it disabled on the Flatpak version)

**Comment by legacychimera247** [comment]
well i'm not in a hurry for this, i just tought you wanted to know...

**Comment by Solarunit** [comment]
MP3 support would be nice

**Comment by Taiko2k** [comment]
@legacychimera247 I understand. I just think its a little unacceptable if major features are not working. It could be quite frustrating for someone if they were relying on it. So I like to get those fixed quickly.

**Comment by legacychimera247** [comment]
what about having a progress bar or something similar?

**Comment by Taiko2k** [comment]
I agree, Ive added a more detailed progress bar that now shows the progress of the folder. Though still not showing progress of individual tracks since that would be harder to do, and also I think modern processors are fast enough where its not really needed.

![Screenshot from 2019-04-12 23-32-13](https://user-images.githubusercontent.com/17271572/56034470-782bae80-5d7b-11e9-874a-6d0e4c2e6091.png)
