### ISSUE TITLE
Minimize button doesn't work on first click

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#93]
Minimize button doesn't work on first click.
v4.1.1

**Comment by Taiko2k** [comment]
I think I know what you mean, it only does it sometimes but not every time, right?

**Comment by Solarunit** [comment]
every time for me

**Comment by Taiko2k** [comment]
what if you click within the window somewhere, then try click minimize?

**Comment by Solarunit** [comment]
Yes, it works when I click on the playlist, but not when I click on the top bar.

**Comment by Taiko2k** [comment]
I mean, does it work on the first click to minimize, if you first click on the playlist?

**Comment by Solarunit** [comment]
Yes.
BTW looks like I also can't select anything in the playlist on the first click.

**Comment by Taiko2k** [comment]
OK, then we have the same issue, I will look into it.

**Comment by smaragdus** [comment]
@Taiko2k 

**Problem**
I experience the same problem (under Windows 8 x64) with `Minimize to tray` enabled. At first I was blaming my system since I had not restarted my machine for quite some time.

**Details**
After fresh start minimize button works fine when used for the first time. After the program has been restored from tray two clicks on minimize button are needed. When `Minimize to tray` is not enabled minimize button works just fine. So I suppose that the problem should have something in common with #78 (_Sytem Tray (Windows)_). I don't know whether this is intended but even when `Minimize to tray` is not enabled **Tauon Music Box** still shows its icon in tray although program minimizes to task bar.

**Another Problem**
After playing for a while with minimize and restarting the program finally the main window got severely distorted, screens:

![snipaste-2019-04-15_205827](https://user-images.githubusercontent.com/9025757/56155315-502e8c00-5fc3-11e9-9594-8fff0548a330.png)

![snipaste-2019-04-15_205900](https://user-images.githubusercontent.com/9025757/56155326-558bd680-5fc3-11e9-8a26-2543541078a1.png)

![snipaste-2019-04-15_205925](https://user-images.githubusercontent.com/9025757/56155335-5ae92100-5fc3-11e9-850f-e3b41d6ca2c6.png)

and I had to delete all settings and start afresh.

**Workaround**
As of version [4.1.1](https://github.com/Taiko2k/TauonMusicBox/releases/tag/v4.1.1) disabling `Minimize to tray` option resolves the problem.

**Comment by smaragdus** [comment]
@Taiko2k 

I reported another probably related issue [here](https://github.com/Taiko2k/TauonMusicBox/issues/78#issuecomment-483365114).

**Comment by Taiko2k** [comment]
@smaragdus I don't believe this is the same issue. 

I've not experienced the clicking to minimize to tray issue in Windows in my testing. So I'm not sure whats going on there. (But I'm almost certain its a separate issue)

Ive had that distortion on rare occasion, I thought I had solved it... I can try make some further adjustments to avoid it.

As for the tray always being on, that was intentional so that those tray controls will persist even if the window was raised. Do you think it should only appear when minimized to tray?

**Comment by smaragdus** [comment]
@Taiko2k 

About the distorted window- I suppose that it happened because I probably restarted the program before it was actually exited. Later I started to monitor the process in a process manager to be sure that the process was terminated but this occurred to me too late. Do you think that this might be the cause of the distorted window?

> As for the tray always being on, that was intentional so that those tray controls will persist even if the window was raised. Do you think it should only appear when minimized to tray?

For me it doesn't matter since `Minimize to tray` option it is always on. I suppose that the users who have not enabled this option do not need tray control (which is indispensable for me) but this is just speculation.

**Comment by Taiko2k** [comment]
As for this original issue, I have fixed this now, so ill be out in the text release.
