### ISSUE TITLE
organize artists by artists and years

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#96]
i generally like to have artists organized alphabetically and albums by yearfrom oldest to newest, and tauon actually do that, but fr doing that i actually need to sort everything by filepath and then sort artists by year. It would be nice o have a direct button for diong tht or make the application remember the choiche so we don't have to do that double click trough menues.

(i know it actually remember that, but sometimes, i dunno why, i find albums displayed as top rated, the first in the sort page)

**Comment by Taiko2k** [comment]
So, there's currently `Sort by filepath` and `Sort year per artist`. Do you have a suggestion on what that should be changed to?

For context, I previously did have these two combined as one function called `Standard Sort`, but maybe the issue is that didn't explain well what the function actually does, or maybe that doesn't matter.

**Comment by legacychimera247** [comment]
what i mean was, for sorting artists and albums this way i need to actually
1 sort by filepath
2 sort artists by year

considering i do think it's a common way of organizing records would be nice to have a single button for doing that, but considering you have linked this one to the other report i think i can close this one?

**Comment by legacychimera247** [comment]
this is working flawlessy, thanks

**Comment by sgreenden** [comment]
I am confused how this is supposed to work, 
![image](https://github.com/Taiko2k/TauonMusicBox/assets/56249225/cfec0c87-e22c-4cf2-a8a6-f93c5610e514)
I want to have it sorted alphabetically so that albums by the same artist are next to each other, preferably in year order but that isn't a huge thing, but nothing seems to happen when I hit "Sort by year per artist". Before there were columns so I could do it that way, I am fine with this UI look, but it doesn't seem to sort. I am using the flatpak on debian btw.

**Comment by Taiko2k** [comment]
@sgreenden Typically if your music library folders were already organised by ARTIST > ALBUM. Then doing a stort by filepath would achieve sorting by artist.

You can also sort using the columns, press the MENU button, the click the toggle icon with the vertical bars. After you hav sorted by a column you can then do the sort year per artist function.

**Comment by sgreenden** [comment]
Thanks, that worked! Will this persist?

**Comment by Taiko2k** [comment]
> Thanks, that worked! Will this persist? I like the look without the columns more, but like this method of sorting.

All sorting in Tauon is in-place and not transient. So it will stay like that until you apply anything else that changes it. You can close the columns view once you're done.

**Comment by sgreenden** [comment]
I've noticed that I can sort it by artist but it's not actually useful because after I add something to a playlist from the main playlist/library it will reset the ordering immediately after, so I don't think this feature has utility.

**Comment by Taiko2k** [comment]
> I've noticed that I can sort it by artist but it's not actually useful because after I add something to a playlist from the main playlist/library it will reset the ordering immediately after, so I don't think this feature has utility.

You might have pressed the "make playlist auto sorting" button at some point. Anyway, what I might suggest is keeping two playlists, one as your main one you import music to, and the other as a ***smart playlist*** that does the sorting you desire.

To set this up:
 1. Press <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>E</kbd>.
 2. Type  `a "artist"> ypa auto`  then <kbd>Enter</kbd> or click away.
