### ISSUE TITLE
Transform play and pause buttons into a single button

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#97]
well the title says it all, the play button just play a song and the pause one just pause it, it would be nice to blend these two together so a single button could play pause the current song, which i guess, is how most people are used to...

**Comment by Taiko2k** [comment]
I specifically prefer it the way it is. As for providing a setting for this, I don't think its really worth the trouble since the current layout functions well. It would also kind of work against the static style of the current design.

Though I wouldn't say an alternate layout is out of the the question for the future.

(And I wouldn't say that combining it is what all people are used to or the implication that it is necessarily a good thing, its a relatively recent design trope I think. The design of Tauon already sets a precedent for disregarding what people may be used to anyway.)

**Comment by legacychimera247** [comment]
ok, i'm fine about this :)
